### ISSUE TITLE
Support for remote files via TRAMP?

### ISSUE THREAD

**Issue by root42** [company-mode/company-mode#462] opened 2016-01-29 12:19 UTC
I am editing quite big C++ projects via ssh / TRAMP using Emacs. I have set up company and clang in principle. When editing a project locally, everything works fine, e.g. #includes are found.

However when editing my remote project, clang failes, because it cannot find the includes. In the clang-error buffer I can see that my local clang is called, instead of the remote one, which probably already would alleviate the problem:

`clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:229:7 -

<stdin>:17:10: fatal error: 'foo/bar.h' file not found
# include <foo/bar.h>

```
     ^`
```

Is there a way to run the clang command remotely? When using (shell-command ...) in a remote buffer, this will usually launch a remote shell, which I use e.g. to find tags with GNU global. So I think this behavior should be possible.

**Comment by root42** [comment] 2016-01-29 12:34
It seems to me that something could be achieved if the usage of start-process is substitued with start-file-process (in [line 221 of company-clang.el](https://github.com/company-mode/company-mode/blob/master/company-clang.el#L211])).

According to the [Emacs Lisp documentation](https://www.gnu.org/software/tramp/#Remote-processes) this function will be treated by TRAMP if the default directory is remote, which should be the case when editing a remote buffer.

**Comment by dgutov** [comment] 2016-01-29 14:04
> the usage of start-process is substitued with start-file-process

Sounds about right. Could you try it out?

**Comment by root42** [comment] 2016-02-05 15:16
> > the usage of start-process is substitued with start-file-process

> Sounds about right. Could you try it out?

I have tried it, but so far with no success. Company gives me this:

```
Company: An error occurred in auto-begin
Writing to process: bad file descriptor, company-clang
company-begin-backend: Cannot complete at point
```

And clang outputs this:

```
clang failed with error 1:
clang -fsyntax-only -Xclang -code-completion-macros -x c++ - -Xclang -code-completion-at=-:2288:13 -

clang-3.8: error: no input files
```

It seems that the stdin gets lost on the way. I am a bit at a loss here. Perhaps this is easy to fix, but I would need some help here -- maybe there are some people with experience in elisp and tramp?

What definitely works seems to be the default-directory. It is correctly set depending on the buffer. Local buffers look like `/Users/$USER/path/to/my/code` and remote buffers will show soemthing like `/scp:myremotehost:/path/to/my/code`. I checked this by debugging the `company-clang--start-process` function.

Also, the `company-async-timeout` variable needs a bump or it needs to be configurable. I've bumped it to 5 seconds, because ssh will be too slow otherwise and company will run into a timeout.

**Comment by dgutov** [comment] 2016-02-05 16:44
> Writing to process: bad file descriptor, company-clang

But it works fine locally?

> Also, the company-async-timeout variable needs a bump or it needs to be configurable. I've bumped it to 5 seconds, because ssh will be too slow otherwise and company will run into a timeout.

Isn't 5 seconds a bit too long to wait for completions? Anything above 1 second seems unfriendly to me.

**Comment by juergenhoetzel** [comment] 2016-02-14 22:12
Works for me when replacing ```start-process``` with *tramp-aware* ```start-file-process```

Completion is slow but usable. A workaround could be to start the async *clang* process in advance.

Another issue is the global value ```company-clang-executable```. If *clang* isn't available on the Emacs host, the backend can't be used on remote hosts.

**Comment by juergenhoetzel** [comment] 2017-01-04 17:11
Should be fixed by [Disable idle completion on remote buffers ](https://github.com/company-mode/company-mode/pull/627)

Pease remember that  you have to trigger completion explicitly. Rationale: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23006#56

**Comment by dgutov** [comment] 2017-01-04 21:03
> Should be fixed by Disable idle completion on remote buffers

This bug report does not ask to disable idle completion.

> Rationale: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23006#56

I don't see that message saying that. Rather, it suggests binding `non-essential` to `t` when we are performing idle completion, so that the completion functions don't try too hard. In the example given, TRAMP would not ask for the password if the connection is not already established.

Looking at the rest of the discussion, though, I'm not sure TRAMP will behave as expected.

**Comment by dgutov** [comment] 2017-01-04 21:05
> it suggests binding non-essential to t when we are performing idle completion

And we do that since 7d2d49bea57acd8f9ea07a8286144ee3ae1110c8.

**Comment by juergenhoetzel** [comment] 2017-01-05 06:45
> Should be fixed by Disable idle completion on remote buffers
> This bug report does not ask to disable idle completion.
> 
> Rationale: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23006#56
> I don't see that message saying that. Rather, it suggests binding non-essential to t when we are performing idle completion, so that the completion functions don't try too hard. In the example given, TRAMP would not ask for the password if the connection is not already established.

TRAMP always has to start a new connection, when using `start-file-process`. But it only starts a new connection if `non-essential` is `nil`. TRAMP has no way to figure out if this will lead to a password prompt (SSH-multiplexing is enabled by default, so in most cases only the first connection will ask for the password).

You can verify this behavior:

```lisp
(let ((non-essential t)
      (default-directory "/ssh:USER@HOST:"))
  (start-file-process "test" "test" "hostname" ))
```
which leads to subtle bugs like this.

@albinus can maybe clarify the details 

> 
> Looking at the rest of the discussion, though, I'm not sure TRAMP will behave as expected.

**Comment by juergenhoetzel** [comment] 2017-01-05 07:01
> it suggests binding non-essential to t when we are performing idle completion
> And we do that since 7d2d49b.

which is actually the root-cause why idle completion isn't working in TRAMP buffers because it binds`non-essential to `t' .

In this case `backends' will fail to complete even when using `start-file-process'

**Comment by dgutov** [comment] 2017-01-05 07:58
> TRAMP always has to start a new connection, when using start-file-process. But it only starts a new connection if non-essential is nil.

If so, that is unfortunate. But doesn't that make your patch (or part of it) redundant?

> TRAMP has no way to figure out if this will lead to a password prompt

```el
(file-remote-p default-directory nil t)
```

?

> You can verify this behavior:

When there's no buffer `test`, it complains about that. When there is, it prints `<hostname>\n\nProcess test finished` in it. Is that what I should see?

That happens when using an `emacs-25` build. The current `master` instead complains: `tramp-file-name-handler: Setting current directory: No such file or directory, /ssh:USER@HOST:`.

**Comment by albinus** [comment] 2017-01-05 09:10
Dmitry Gutov <notifications@github.com> writes:

Hi Dmitry & Jürgen,

>     TRAMP always has to start a new connection, when using
>     start-file-process. But it only starts a new connection if
>     non-essential is nil.
>
> If so, that is unfortunate. But doesn't that make your patch (or part
> of it) redundant?
>
>     TRAMP has no way to figure out if this will lead to a password
>     prompt
>
> (file-remote-p default-directory nil t)
>
> ?
>
>     You can verify this behavior:
>
> When there's no buffer test, it complains about that. When there is,
> it prints <hostname>\n\nProcess test finished in it. Is that what I
> should see?
>
> That happens when using an emacs-25 build. The current master instead
> complains: tramp-file-name-handler: Setting current directory: No such
> file or directory, /ssh:USER@HOST:.

I'm not a company-mode user, so I cannot comment too much. Could you pls
provide me a step-by-step scenario, that I could see what happens? Thanks.

Best regards, Michael.

**Comment by albinus** [comment] 2017-01-05 10:15
Dmitry Gutov <notifications@github.com> writes:

Hi Dmitry,

> Michael, the "verify this behavior" snippet above does not depend on
> company-mode.

There exist an internal function, which could be used. Something like:

--8<---------------cut here---------------start------------->8---
(let ((non-essential t)
      (default-directory "/ssh::"))
  (if (tramp-connectable-p default-directory)
      (start-file-process "test" (current-buffer) "hostname" )))
--8<---------------cut here---------------end--------------->8---

This doesn't call `start-file-process'. If you don't bind
`non-essential', `start-file-process' is invoked.

I have mixed feelings to use an internal Tramp function somewhere else,
but there isn't something better yet.

Best regards, Michael.

**Comment by dgutov** [comment] 2017-01-05 10:35
Thanks, Michael. That seems to answer the question of whether binding `non-essential` to `t` stops `start-file-process` from working on remote file names.

That's not actually what we wanted to do, AFAIK, so the question of using `tramp-connectable-p` here is moot.

@juergenhoetzel Would you like to add anything?

**Comment by albinus** [comment] 2017-01-05 12:06
Dmitry Gutov <notifications@github.com> writes:

> Thanks, Michael. That seems to answer the question of whether binding
> non-essential to t stops start-file-process from working on remote
> file names.

No, it doesn't. `non-essential' has effect only for file names which
look incomplete. `start-file-process' works over `default-directory',
which isn't incomplete.

Best regards, Michael.

**Comment by juergenhoetzel** [comment] 2017-01-05 17:19
Hi Michael,

> No, it doesn't. `non-essential' has effect only for file names which
> look incomplete. `start-file-process' works over `default-directory',
> which isn't incomplete.

@albinus

So is the following conditional in `tramp-maybe-open-connection` a bug?

```lisp
(when (and (boundp 'non-essential) (symbol-value 'non-essential))
	   (throw 'non-essential 'non-essential))
```

Because via `tramp-file-name-handler` the default handler is invoked
if `non-essential` is thrown:

```lisp
;; In both cases, we try the default handler then.
(setq result
	    (catch 'non-essential
	      (catch 'suppress
		(apply foreign operation args))))
(cond
 ((eq result 'non-essential)
	(tramp-message
	 v 5 "Non-essential received in operation %s"
	 (cons operation args))
	(tramp-run-real-handler operation args))
```

```
TRAMP log: 17:50:28.874183 tramp-file-name-handler (5) # Non-essential received in operation (start-file-process test test hostname)
```
which seems to be the root cause of this issue (clang is executed on the
local machine).

BTW, I interpreted `non-essential` docstring in a wider sense:

> This variable should be non-nil only when running code which should not
> disturb the user.  E.g. it can be used to **prevent Tramp from prompting the
> user for a password** when we are simply scanning a set of files in the
> background or ** displaying possible completions before the user even asked
> for it**.

This might happen in company idle-completion. So I disabled
idle-completion for remote buffers in the original pull request.

**Comment by albinus** [comment] 2017-01-06 09:32
Jürgen Hötzel <notifications@github.com> writes:

> Hi Michael,

Hi Juergen,

>     No, it doesn't. non-essential' has effect only for file names
>     which look incomplete.start-file-process' works over
>     `default-directory',
>     which isn't incomplete.
>
> So is the following conditional in tramp-maybe-open-connection a bug?
>
> (when (and (boundp 'non-essential) (symbol-value 'non-essential))
> 	   (throw 'non-essential 'non-essential))

No, this is proper. Tramp interprets non-essential being non-nil as an
indication, *not* to open a new connection if not established
yet. That's OK most cases I believe.

> BTW, I interpreted non-essential docstring in a wider sense:
>
>     This variable should be non-nil only when running code which
>     should not
>     disturb the user. E.g. it can be used to prevent Tramp from
>     prompting the
>     user for a password when we are simply scanning a set of files in
>     the
>     background or ** displaying possible completions before the user
>     even asked
>     for it**.

However, thinking more about (I did it the whole last night), I believe
Tramp is inconsistent here. If somebody calls `start-file-process' (or
`process-file'), she shows explicitely her will to open a new
connection. This shall be accepted by Tramp, and I believe we need the
following patch:

--8<---------------cut here---------------start------------->8---
diff --git a/lisp/tramp-sh.el b/lisp/tramp-sh.el
index fec9f10..48c00fc 100644
--- a/lisp/tramp-sh.el
+++ b/lisp/tramp-sh.el
@@ -2836,7 +2836,8 @@ the result will be a local, non-Tramp, file name."
 (defun tramp-sh-handle-start-file-process (name buffer program &rest args)
   "Like `start-file-process' for Tramp files."
   (with-parsed-tramp-file-name (expand-file-name default-directory) nil
-    (let* ((buffer
+    (let* (non-essential
+	   (buffer
 	    (if buffer
 		(get-buffer-create buffer)
 	      ;; BUFFER can be nil.  We use a temporary buffer.
@@ -2972,7 +2973,8 @@ the result will be a local, non-Tramp, file name."
     (error "Implementation does not handle immediate return"))
 
   (with-parsed-tramp-file-name default-directory nil
-    (let (command env uenv input tmpinput stderr tmpstderr outbuf ret)
+    (let (command env uenv input tmpinput stderr tmpstderr outbuf ret
+	  non-essential)
       ;; Compute command.
       (setq command (mapconcat 'tramp-shell-quote-argument
 			       (cons program args) " "))
--8<---------------cut here---------------end--------------->8---

Would this help in your use case?

Best regards, Michael.

**Comment by dgutov** [comment] 2017-01-06 14:17
> If somebody calls `start-file-process' (or `process-file'), she shows explicitely her will to open a new connection.

But those are not interactive functions. Lisp code calls them, and it can happen in many different circumstances. Even in those, like we have in the case of idle-completion, that are considered "non-essential".

**Comment by juergenhoetzel** [comment] 2017-01-06 18:40
> If somebody calls start-file-process' (orprocess-file'), she shows explicitely her will to open a new connection.

@albinus 
with your patch *idle-completion* works fine now.
> But those are not interactive functions. Lisp code calls them, and it can happen in many different circumstances. Even in those, like we have in the case of idle-completion, that are considered "non-essential".

It would still be possible the user get **disturbed** by a password prompt while in `idle-completion`?

**Comment by dgutov** [comment] 2017-01-06 18:50
> It would still be possible the user get disturbed by a password prompt while in idle-completion?

That is essentially the question that I'm asking, yes.

**Comment by albinus** [comment] 2017-01-06 19:22
Dmitry Gutov <notifications@github.com> writes:

>     If somebody calls start-file-process' (orprocess-file'), she shows
>     explicitely her will to open a new connection.
>
> But those are not interactive functions. Lisp code calls them, and it
> can happen in many different circumstances. Even in those, like we
> have in the case of idle-completion, that are considered
> "non-essential".

But this is the responsibility  of the library then, isn't it? I haven't
seen such problem reports yet, so company-mode seems to be different to
the other libraries. I'm open to everything what fits best.

Best regards, Michael.

PS: I'm still not familiar with your slang, like "idle-completion" ...

**Comment by dgutov** [comment] 2017-01-06 21:08
> I haven't seen such problem reports yet, so company-mode seems to be different to the other libraries.

It's not a library, it's a framework. The relevant difference is that we use third-party code, and do that automatically.

While we can choose not to use `start-file-process` at all when remote in `company-clang` (not sure that's a great idea anyway), we can't make that choice for all other completion functions we use through `company-capf` (the elements of the `completion-at-point-functions` hook).

What we can do it do bind some variable to a value, to indicate user intent. And we already bind `non-essential` to t when performing idle completion.

> I'm still not familiar with your slang, like "idle-completion"

That's simple: it's the process of showing a visualization with the list of completions after user has typed something and then leaves Emacs idle for a bit (by default, for 0.3 seconds).

Our default visualization is popup-like, inside a buffer window. A related example is completion hints shows by icomplete for minibuffer input, like discussed in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23006#56.

**Comment by albinus** [comment] 2017-01-07 16:50
Dmitry Gutov <notifications@github.com> writes:

> What we can do it do bind some variable to a value, to indicate user
> intent. And we already bind non-essential to t when performing idle
> completion.

The current Tramp implementation suppresses `start-file-process' when
`non-essential' is non-nil, even if there exists already a connection to
the remote host. The following patch should fix this:

--8<---------------cut here---------------start------------->8---
diff --git a/lisp/tramp-sh.el b/lisp/tramp-sh.el
index fec9f10..3f4e655 100644
--- a/lisp/tramp-sh.el
+++ b/lisp/tramp-sh.el
@@ -4655,7 +4655,11 @@ connection if a previous connection has died for some reason."
 
 	  ;; If `non-essential' is non-nil, don't reopen a new connection.
 	  ;; This variable has been introduced with Emacs 24.1.
-	  (when (and (boundp 'non-essential) (symbol-value 'non-essential))
+	  ;; We check this for the process related to
+	  ;; `tramp-buffer-name'; otherwise `start-file-process'
+	  ;; wouldn't run ever when `non-essential' is non-nil.
+	  (when (and (boundp 'non-essential) (symbol-value 'non-essential)
+		     (null (get-process (tramp-buffer-name v))))
 	    (throw 'non-essential 'non-essential))
 
 	  (with-tramp-progress-reporter
--8<---------------cut here---------------end--------------->8---

Comments?

Best regards, Michael.

**Comment by dgutov** [comment] 2017-01-07 17:09
Sounds good to me, thanks.

@juergenhoetzel Could you test the patch?

**Comment by juergenhoetzel** [comment] 2017-01-07 17:36
>    (null (get-process (tramp-buffer-name **v**))))

I suppose the **v** is a typo:

Using
`(null (get-process (tramp-buffer-name vec)))`
your patch works fine for me: 

Thanks Michael!

**Comment by albinus** [comment] 2017-01-07 17:54
Jürgen Hötzel <notifications@github.com> writes:

> I suppose the v is a typo:

Of course, thanks for checking!

> Using
> (null (get-process (tramp-buffer-name vec)))
> your patch works fine for me:

I've committed the patch to both Tramp and Emacs repository.

> Thanks Michael!

Best regards, Michael.

**Comment by juergenhoetzel** [comment] 2017-01-09 10:17
Idle completion works fine now using the latest *TRAMP* commit.

There is always an established connection when using idle completion (triggered by opening the remote file, the user is editing): So I propose to use the  *TRAMP*-aware `start-file-proces` in #629 , label this issue as *Upstream* bug and close it.

**Comment by dgutov** [comment] 2017-01-09 11:35
Thank you. I suppose that just leaves the problem of the `company-clang-executable` variable.

But the user can change it locally. Not sure that it warrants some deeper solution.

**Closed by dgutov** 2017-01-09 11:35 UTC

**Comment by dgutov** [comment] 2017-01-09 11:38
> label this issue as Upstream bug

That would be a bit misleading. We had a problem here ourselves. It's just that our fix depends on a recent-enough TRAMP.

**Comment by albinus** [comment] 2017-01-09 13:11
Dmitry Gutov <notifications@github.com> writes:

> Thank you. I suppose that just leaves the problem of the
> company-clang-executable variable.
>
> But the user can change it locally. Not sure that it warrants some
> deeper solution.

You could document it as connection-local variable. This requires Emacs
26, 'tho.

Best regards, Michael.

**Comment by dgutov** [comment] 2017-01-09 22:15
OK, thanks. Looking at `with-connection-local-classes`, though, it seems I can't easily use it while supporting older versions of Emacs.

**Comment by gongzhitaao** [comment] 2022-08-16 19:53
I think it is better to have an option for whether it would be TRAMP-aware or not.

I'm editing remote files and the completion is barely usable because it is _really_ slow.  I have to turn it off.  Most of the time, I just need completion that is from the context.

What do you all think?

**Comment by dgutov** [comment] 2022-08-16 21:40
@gongzhitaao Making `gtags` non-tramp aware means it won't work on remote hosts at all. Same for `company-clang` or `company-cmake`.

You can change the list of backends in `find-file-hook` and choose the ones that will work locally if the file is remote.

I suppose we could add some user option, but we'd have to choose the semantics first.
