### ISSUE TITLE
autocomplete doesn't work if cursor is followed by letters

### ISSUE THREAD

**Issue by codersam88** [company-mode/company-mode#539] opened 2016-06-09 03:59 UTC
Hi,
I've noticed this behavior of company mode where it doesn't give prediction when the cursor is in the middle of the word and cursor is followed by letters. 
![wordmiddle](https://cloud.githubusercontent.com/assets/1143331/15918443/6eb024aa-2e24-11e6-8df1-8e6e9799bd1e.png)

I could see it can complete if the cursor is in the middle of the word but followed by special symbols like 
. _ etc 
![word2](https://cloud.githubusercontent.com/assets/1143331/15918460/95a47eda-2e24-11e6-92f5-49c60900112a.png)

Can it be changed so that it can give predictions even when cursor is in the middle of the world. 
Thanks

**Comment by dgutov** [comment] 2016-06-20 04:17
Duplicate of https://github.com/company-mode/company-mode/issues/340.

**Closed by dgutov** 2016-06-20 04:17 UTC
