### ISSUE TITLE
No candidates are displayed when the word starts with a special character

### ISSUE THREAD

**Issue by ig-perez** [company-mode/company-mode#1068] opened 2021-03-01 15:38 UTC
Hi, thanks for maintaining this package!

I write in English and Spanish, so I made a function to easily switch the `Flyspell` dictionary and use a list of words as a backend for `Company`.

This is one of the functions I use:
```emacs-lisp
(defun ivan/español ()
  "A function to set a writing environment in Spanish"
  (interactive)
  
  (setq-local company-ispell-dictionary (file-truename "~/.emacs.d/ivan/es.dict"))
  (ispell-change-dictionary "es")
  (setq company-minimum-prefix-length 4)
  (set (make-local-variable 'company-backends) '(company-ispell company-dabbrev-code))
  )
```

Everything is working fine except when the word starts with an accented character like `índice`or `ñandú`. In both cases no candidates are shown and a message appears in the modeline: `Starting "look" process ...`

Am I doing something wrong?

This is how the Spanish dictionary looks like:
```
...
átomo
átomos
átona
átonas
átono
átonos
áulica
áulicas
...
```

Thanks!

**Comment by dgutov** [comment] 2021-03-02 01:29
Hi!

There might be some problem with dictionary condents' encoding. If you know how to use Edebug, you might be well-positioned to work out where the misbehavior starts.

If not, we can start with a primitive provided by Emacs core. Does `M-x ispell-complete-word` work for you? Just make sure to customize the appropriate variable: either `ispell-alternate-dictionary` or `ispell-complete-word-dict`.

**Comment by ig-perez** [comment] 2021-03-02 18:31
Hi @dgutov thanks for your reply and sorry, but I have practically no experience with `Edebug` yet.

I was reading the documentation of the involved variables (confusing I have to say) and I decided to only use `ispell-complete-word-dict` because when `company-ispell-dictionary` is set to `nil`, `ispell-complete-word-dict` will be used as a fallback, so now I have:

```emacs-lisp
  (setq-local company-ispell-dictionary nil)
  (setq-local ispell-complete-word-dict (file-truename "~/.emacs.d/ivan/es.dict"))
```
With this, `M-x ispell-complete-word` works but ignores the first letter when it contains special characters:
![image](https://user-images.githubusercontent.com/33359427/109695190-9f4f1d00-7b59-11eb-937f-839b963edd5c.png)
As you can see, none of the suggestions start with `á`.

I have also seen this odd behavior (with the message `Starting "look" process ...`) with words without accented characters, for example when writing `sugie` and then `M-x ispell-complete-word` I get `No match for "sugie"`, but the word is in the dictionary, and as you can see, it doesn't contain special characters.:
![image](https://user-images.githubusercontent.com/33359427/109695606-197fa180-7b5a-11eb-94ac-5a1b0316666f.png)

**Comment by dgutov** [comment] 2021-03-02 21:12
> With this, M-x ispell-complete-word works ...

And `company-ispell` works with it too?

> ... but ignores the first letter when it contains special characters

That sounds like a good cause for an Emacs bug report, then. Could you `M-x report-emacs-bug`, repeating the necessary steps to reproduce the problem with `M-x ispell-complete-word`?

It also might be important to mention where/how you got the dictionary from.

**Comment by ig-perez** [comment] 2021-03-03 14:16
I just tried `company-ispell`and it is not working, when executing it I get:

```
Starting "look" process...
No completion found
user-error: Cannot complete at point
```

But `M-x ispell-complete-word` shows the candidates.

I got my dictionary from `aspell`.

With this last update, should I still create a bug on `Emacs`?

**Comment by dgutov** [comment] 2021-03-03 16:18
> With this last update, should I still create a bug on Emacs?

If `M-x ispell-complete-word` fails in a number of cases where it should work - yes, of course.

I'll take a look at `company-ispell` problem too, but it's likely dependent on ispell being fixed in Emacs anyway.

> I got my dictionary from aspell.

I have the `aspell` package installed, and yet there is no `es.dict` anywhere inside my `/usr`.

**Comment by ig-perez** [comment] 2021-03-03 16:37
Ok, I'll create the issue as soon as I can. About the dictionary, I followed these steps:
1. `$ sudo dnf install aspell aspell-en aspell-es enchant-aspell enchant2-aspell`
2. I changed the `enchant.ordering` file so it prefers `aspell` instead of `hunspell`
3. `(setq-default ispell-program-name "aspell")`
4. I generated a plain ES dictionary from `aspell` installed dictionary with
    ```shell
    $ aspell -d es dump master | aspell -l es expand | tr -s '[:space:]' '\n' | LC_ALL=C sort -S28G -u > es.dict
    ```

**Comment by dgutov** [comment] 2021-03-04 00:26
Thanks.

Well, I did

```el
(setq-local company-ispell-dictionary nil)
(setq-local ispell-complete-word-dict (file-truename "~/es.dict"))
;; ispell-program-name is at its default (which is `"/usr/bin/aspell"`)
```

with the dictionary generated using your recipe, and completion seems to work. Like, I paste `ín` into the `*scratch*` buffer, type `M-x company-ispell`, and it shows completions. I had to, at one time, toggle `company-mode` off and on because of some uncaught error in its post-command hook. But I couldn't reproduce this in the next Emacs session where I repro'd the process.

```sh
$ aspell --version
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
```

**Comment by ig-perez** [comment] 2021-03-04 22:21
This is odd, perhaps there is something else interfering. This is my company-related configuration, notice something wrong?
```emacs-lisp
;; Company for completion
(use-package company
  :ensure t
  :config
  (add-hook 'after-init-hook 'global-company-mode)
  :custom
  (company-minimum-prefix-length 2)
  (company-idle-delay 0.0)
  ;;:custom-face
  ;;(tooltip ((t (:height 0.9))))  ;; We can reduce the candidates font-size here, but company-box override this values!
  )

;; Add documentation in popups
(use-package company-quickhelp
  :after company
  :ensure t
  :config
  (company-quickhelp-mode)
  )

;; Doesn't work properly because Wayland (see below)
(use-package company-box
  :after company
  :ensure t
  :hook (company-mode . company-box-mode)
  :config
  (setq company-box-show-single-candidate t)
  (setq x-gtk-resize-child-frames 'hide)	;; This solves the variable scrollbar width. This is probably related to Wayland

  (add-to-list					;; Font-size: It seems the faces of company-box override the ones in Company		
   'company-box-frame-parameters		;; then, it is better to set the font size of the dropdown list of candidates
   '(font . "JetBrains Mono-11")		;; and documentation box here. Company-box doesn't expose faces! This seems to be the only way
   )
  )
```

Then the spellchecking config:
```emacs-lisp
;; Flyspell for spell checking. Already included in Emacs, just some tweaks
(setq flyspell-issue-message-flag nil)				;; Printing messages for every word (when checking the entire buffer) causes an enormous slowdown!

;; Use GNU aspell for spellchecking
(setq-default ispell-program-name "aspell")

(defun ivan/español ()
  "A function to set a writing environment in Spanish"
  (interactive)
  
  (setq-local company-ispell-dictionary nil)						;; When nil, it will use ispell-complete-word-dict as fallback
  (setq-local ispell-complete-word-dict (file-truename "~/.emacs.d/ivan/es.dict"))

  
  (ispell-change-dictionary "es")
  (setq company-minimum-prefix-length 4)
  (set (make-local-variable 'company-backends) '(company-ispell company-dabbrev-code))
  )

(defun ivan/ingles ()
  "A function to set a writing environment in English"
  (interactive)

  (setq-local company-ispell-dictionary nil)						;; When nil, it will use ispell-complete-word-dict as fallback
  (setq-local ispell-complete-word-dict (file-truename "~/.emacs.d/ivan/en.dict"))

  (ispell-change-dictionary "en")
  (setq company-minimum-prefix-length 2)
  (set (make-local-variable 'company-backends) '(company-ispell company-dabbrev-code))  
  )

(defun ivan/restaurar-company-backends ()
  "A function to restore default Company backends"
  (interactive)

  (setq company-minimum-prefix-length 2)
  (set (make-local-variable 'company-backends) '(
                                                 company-bbdb
                                                 company-semantic
                                                 company-cmake
                                                 company-capf
                                                 company-clang
                                                 company-files
                                                 (company-dabbrev-code company-gtags company-etags company-keywords)
                                                 company-oddmuse
                                                 company-dabbrev
                                                 )
       )
  )
```

**Comment by dgutov** [comment] 2021-03-04 22:46
Nothing really jumps out.

But the canonical way is to approach this from the other direction. You launch `emacs -Q` and step-by-step build the smallest possible configuration that lets you reproduce the problem.

**Comment by ig-perez** [comment] 2021-03-04 23:33
Ok, I'll check that out as soon as I can.

**Comment by ig-perez** [comment] 2021-03-06 16:39
Hi @dgutov , I'm puzzled, I'm starting emacs with `emacs -q -l ~/.emacs.d/ivan/spellchecking.el`:
```emacs-lisp
(require 'package)

(setq debug-on-error t
      no-byte-compile t
      package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/"))
      package-user-dir (expand-file-name (make-temp-name "ivan-tmp-elpa")
                                         user-emacs-directory)
      custom-file (expand-file-name "custom.el" package-user-dir))

(let*
  ;; Bare minimum
  ((pkg-list '(company)))
  
  ;; Body to eval after binding
  (package-initialize)
  (package-refresh-contents)

  (mapc (lambda (pkg)
          (unless (package-installed-p pkg)
            (package-install pkg))
          (require pkg))
        pkg-list)

  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t)))
)

;; Use GNU aspell for spellchecking
(setq-default ispell-program-name "aspell")

(defun ivan/español ()
  "A function to set a writing environment in Spanish"
  (interactive)
  
  (setq-local company-ispell-dictionary nil)
  (setq-local ispell-complete-word-dict (file-truename "~/.emacs.d/ivan/es.dict"))

  
  (ispell-change-dictionary "es")
  (setq company-minimum-prefix-length 4)
  (set (make-local-variable 'company-backends) '(company-ispell company-dabbrev-code))
  )

  
(provide 'spellchecking)
```
As you can see, I'm just installing `Company` but the error is still there. The completions are shown with `ispell-complete-word`, but none of them start with `ín`. `company-ispell` is not working:
![image](https://user-images.githubusercontent.com/33359427/110213584-a84c3100-7e6e-11eb-92e3-e9812f12c43f.png)

I have no clue why it is working for you. Can you share your `dict` file so I can try out with that?

Thanks

**Comment by dgutov** [comment] 2021-03-10 02:52
> The completions are shown with ispell-complete-word, but none of them start with ín. company-ispell is not working

Both work here. Since we're testing `M-x company-ispell`, even `company-backends` configuration is not needed.

> Can you share your dict file so I can try out with that?

I've uploaded it here: https://filetransfer.io/data-package/Yvh7fSsy#link

**Comment by dgutov** [comment] 2021-05-10 01:57
@ig-perez Any news?

**Comment by ig-perez** [comment] 2021-05-10 02:10
Hi @dgutov, sorry I haven't had the chance to check this. If you prefer please close the issue, I'll create a new one or re open it when I have the opportunity to check this again

**Closed** 2023-09-29 23:57 UTC
Labels: invalid
