### ISSUE TITLE
error "Marker does not point anywhere" with args (post-completion if)

### ISSUE THREAD

**Issue by thomasheartman** [company-mode/company-mode#1043] opened 2020-12-26 12:00 UTC
Hi,

# Issue

When using [Rust Analyzer's](https://github.com/rust-analyzer/rust-analyzer) post-completion functionality, I came across an issue where it seemingly doesn't work unless the previous action removed text from the buffer.

More specifically, given this scenario (inside a function and where `|` is the cursor):
```rust
true.if|
```

I can trigger `company-complete` to get the list of completion candidates (which contains a single item). If I try to `company-complete-selection`, I get an error message saying

```
company-call-backend-raw: Company: backend company-capf error "Marker does not point anywhere" with args (post-completion if)
```

However, if I add a character and then delete it, say `true.if` -> `true.ifh` -> `true.if`, expanding the snippet works just fine. The same happens if what I delete is elsewhere in the buffer too (such as on a different line) and it doesn't seem to matter what character it is (whitespace or otherwise).

## Update  

It turns out that as long as I enter any characters after if (e.g. `true.ifh`) and move the cursor back to before the extra characters, expansions works as expected and removes the remaining characters: `true.if|h` -> `company-complete-selection` becomes

```rust
if true {

}
```

If a string follows the `if`, then it remains intact for some reason. `true.if"string"` becomes:
```rust
if true {

}"string"
```

# Resolutions and general thoughts

I have tried to look around (both online and in the source code), but haven't been able to identify what's going on (or even debug it very well). Would you happen to have any idea what's going on? 

I also realize that this might be a lsp-mode or rust-analyzer issue and not a company-mode issue, but because I'm not sure exactly what I'm looking at, I thought I'd start here.

I appreciate any input you may have. If I can provide you with additional information, please do not hesitate to ask and I shall give you what I can.

# System info

**Emacs version**: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)

Thanks for the help and for the great package!

**Comment by dgutov** [comment] 2020-12-26 19:16
Hi!

What does `M-x company-diag` say?

**Comment by thomasheartman** [comment] 2020-12-27 15:27
Ah, of course. Sorry for not including that in the first place. 

`M-x company-diag` says:

```
Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-12-27 on nil
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: rust-mode
Prefix: ("if" . t)

Completions:
  #("if" 0 2 (lsp-completion-item #s(hash-table size 12 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("additionalTextEdits" [#s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("newText" "" "range" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("end" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("character" 13 "line" 42)) "start" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("character" 8 "line" 42))))))] "deprecated" nil "detail" "if expr {}" "filterText" #("if" 0 2 (match-data (0 2 0 1 1 2))) "insertTextFormat" 2 "kind" 15 "label" "if" "textEdit" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("newText" "if true {
    $0
}" "range" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("end" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("character" 13 "line" 42)) "start" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("character" 13 "line" 42)))))) "_emacsStartPoint" 1825)) lsp-sort-text nil lsp-completion-start-point 1825 lsp-completion-markers (1825 #<marker (moves after insertion) in no buffer>) lsp-completion-prefix "" face (completions-common-part))) " if expr {} (Snippet)"
```

**Comment by dgutov** [comment] 2020-12-27 16:41
OK, so it's `lsp-mode`. The the problem is probably (though not 100% certainly, of course) in their code.

I suggest you try reporting it to them first, according to their reporting instructions.

**Comment by nbfalcon** [comment] 2020-12-30 15:48
@dgutov The problem is in `lsp-mode` (a marker is deleted causing hanging references), and a [PR](https://github.com/emacs-lsp/lsp-mode/pull/2483) to fix that is in review. You may close this.

**Comment by dgutov** [comment] 2020-12-30 23:53
Thanks, I'll follow up there.

**Closed by dgutov** 2020-12-30 23:53 UTC
Labels: third party issue
