### ISSUE TITLE
company-clang: union completion shows (anonymous) like a method parameter

### ISSUE THREAD

**Issue by huangguiyang** [company-mode/company-mode#628] opened 2017-01-08 09:25 UTC
![union](https://cloud.githubusercontent.com/assets/3087203/21832666/b24dca7e-d7e7-11e6-8696-654e1e462d7e.gif)

but `(anonymous)` is unnecessary.

**Comment by dgutov** [comment] 2017-01-12 23:16
Thank you for the report. The problem is chiefly a result of how we process the type hints included by Clang (i.e. we strip the formatting). I'll have to consider whether to do a "proper" fix, or just work around this particular case.

Have you seen any similar problems, other than in anonymous union completion? Do you encounter this case frequently?

**Comment by huangguiyang** [comment] 2017-01-13 00:28
I have found only this case so far (anonymous struct/union). It really affected my daily use. Waiting for your fix, thanks.

**Comment by dgutov** [comment] 2017-01-13 04:06
I've pushed a fix. Please test, and see if it didn't break anything else.

**Closed** 2017-01-13 04:05 UTC

**Comment by huangguiyang** [comment] 2017-01-13 05:02
It works! Thanks for your work. Hoping the release update from melpa.
