### ISSUE TITLE
company-yasnippet should match full name

### ISSUE THREAD

**Issue by luckyrandom** [company-mode/company-mode#205] opened 2014-10-10 06:05 UTC
Currently, company-yasnippet only match partial snippet name, but complain "cannont complete at point" for full name.

For example, for a snippet named `lisp`, it works well if the word at point is `lis`, but fails for word `lisp`.

**Comment by sixshotx** [comment] 2017-02-28 19:18
I still get confused after reading several issues, but is this problem already solved in the current repo or is there a way to complete the full name matching using company-yasnippet?

**Comment by jojojames** [comment] 2017-07-26 01:19
I'll leave this here in case someone wants to experiment with this.

```
  (defun jj*--company-calculate-candidates (prefix)
    (let ((candidates (cdr (assoc prefix company-candidates-cache)))
          (ignore-case (company-call-backend 'ignore-case)))
      (or candidates
          (when company-candidates-cache
            (let ((len (length prefix))
                  (completion-ignore-case ignore-case)
                  prev)
              (cl-dotimes (i (1+ len))
                (when (setq prev (cdr (assoc (substring prefix 0 (- len i))
                                             company-candidates-cache)))
                  (setq candidates (all-completions prefix prev))
                  (cl-return t)))))
          (progn
            ;; No cache match, call the backend.
            (setq candidates (company--preprocess-candidates
                              (company--fetch-candidates prefix)))
            ;; Save in cache.
            (push (cons prefix candidates) company-candidates-cache)))
      ;; Only now apply the predicate and transformers.
      (setq candidates (company--postprocess-candidates candidates))
      (when candidates
        (if (or (cdr candidates)
                (get-text-property 0 'yas-template (car candidates))
                (not (eq t (compare-strings (car candidates) nil nil
                                            prefix nil nil ignore-case))))
            candidates
          t))))

  (advice-add 'company-calculate-candidates
              :override 'jj*--company-calculate-candidates)
```

Exactly the same function as the original except it checks for the yas-template value in the candidates list.

After that, since I use company-pseudo-tooltip-unless-just-one-frontend-with-delay which is just company-pseudo-tooltip-unless-just-one-frontend, I'd like the tooltip not to be there for regular completions but be there for yasnippet completions. 

So then, I advise this function.

```
  (defun jj*--company-show-inline-p ()
    (and (and (not (cdr company-candidates))
              (not (get-text-property 0 'yas-template (car company-candidates))))
         company-common
         (or (eq (company-call-backend 'ignore-case) 'keep-prefix)
             (string-prefix-p company-prefix company-common))))
  (advice-add 'company--show-inline-p :override 'jj*--company-show-inline-p)
```

Haven't tested it out too much but it seems to be working for the happy cases for me.

**Comment by dgutov** [comment] 2017-08-05 20:28
@jojojames Seems like a good hack. Along the lines of what we discussed in #150, but backend-specific.

**Comment by vemv** [comment] 2018-08-13 04:16
@jojojames , I'm curious, has your code stood the test of time?

**Comment by jojojames** [comment] 2018-08-13 08:14
@vemv Yup.

**Comment by vemv** [comment] 2018-08-18 02:25
Thank you @jojojames . I have tried the patch this week; it works flawlessly.

Wondering if the changes could be merged into company-mode as it's always unsettling to have altered sources (especially in the face of package updates)

**Comment by jojojames** [comment] 2018-08-18 17:29
@vemv @dgutov I think it'd be cool to do so (in the interest of also removing this kind of hack/workaround from my own config) but it's also not generic enough to solve the other case (arglist completion in the other issue thread).

Maybe adding a special case for yasnippet is right here, since it does seem to provide a better user experience (at least for yasnippet).

**Comment by vemv** [comment] 2018-08-23 14:36
@jojojames btw, I found an issue with `jj*--company-calculate-candidates`: if I have a snippet called `t`, and the cursor (`|`) is placed at `abcdeft|`, when hitting TAB I'll get the completion for `t`. It only should be triggered for ` t|`, `(t|`, etc

**Comment by jojojames** [comment] 2018-08-23 16:35
@vemv Doesn't happen for me, you'll have to give me a recipe to debug it.

For example, this doesn't complete for me.

```
(setq company-backends '((company-dabbrev-code :with company-yasnippet)))

; (v for vector)
av| ; no completion
v; completion
```

**Comment by vemv** [comment] 2018-08-23 18:34
I hadn't realised the bug is for a specific case (and possibly other similar ones): clojure keywords containing dots.

So, given a yasnippet called `t`, given the keyword (and cursor position) `:foo.t|`, TAB will complete for `t`, but that doesn't make sense because it is preceded by 5 other characters.

**Comment by jojojames** [comment] 2018-08-24 02:49
@vemv Your tab key is bound to yas-expand right (make sure your cursor is where you placed it)? That sounds like it's a yasnippet bug as I see the same thing even without company.

Using your same snippet, just M-x yas-expand and you should see the same problem.

**Comment by vemv** [comment] 2018-08-24 02:51
Correct! Thank you for the analysis.

**Closed as completed** 2018-12-13 23:25 UTC

**Comment by dgutov** [comment] 2018-12-13 23:47
This takes the behavior to where it satisfies the description in the first post, but still somewhat different from what the advices by @jojojames do. Still, I wouldn't recomment to use them anymore because the relevant code has changed.

Please try the new feature out, and if it still doesn't satisfy someone's workflow, let me know.

**Comment by dgutov** [comment] 2018-12-16 09:47
> ifdef (no tooltip)

If you `M-x company-complete` at that point, it will expand.

> Any tips in this or what to look for would be appreciated here!

If you absolutely need this during idle completion as well, you can advise `company--unique-match-p`.

**Comment by dgutov** [comment] 2018-12-16 10:01
Like this:

```lisp
(defun company--unique-match-p/not-yasnippet (candidates prefix ignore-case)
  (not (get-text-property 0 'yas-template (car candidates))))

(advice-add 'company--unique-match-p :after-while
            'company--unique-match-p/not-yasnippet)
```

**Comment by jojojames** [comment] 2018-12-16 18:05
> If you M-x company-complete at that point, it will expand.

Yeah.

> Like this:

Thanks! This works more or less the same as before for me. Happy to be removing 50-60 lines of advice now. :)

**Comment by rickalex21** [comment] 2023-02-26 16:47
I have the same problem.  @dgutov  thanks, that works. Not sure if by now they fixed this with
a variable we can set or something? It's been 4 years now.

**Comment by dgutov** [comment] 2023-02-27 01:58
The current recommendation is to use `M-x company-complete` (to set up a binding for it).

Is that not comfortable enough for you? Do you type out snippet names in full often during completion?

I suppose we could make yasnippet completions behave differently. I wonder what other backends might want this change, and what to call this property.

**Comment by dgutov** [comment] 2023-02-27 02:00
Actually, we might be able to make the choice based on completion kind.

Try this patch out:

```diff
diff --git a/company.el b/company.el
index 9e98f6a..5de595c 100644
--- a/company.el
+++ b/company.el
@@ -1448,7 +1448,9 @@ update if FORCE-UPDATE."
   (and candidates
        (not (cdr candidates))
        (eq t (compare-strings (car candidates) nil nil
-                              prefix nil nil ignore-case))))
+                              prefix nil nil ignore-case))
+       (not (eq (company-call-backend 'kind (car candidates))
+                'snippet))))
 
 (defun company--fetch-candidates (prefix)
   (let* ((non-essential (not (company-explicit-action-p)))
```

**Comment by rickalex21** [comment] 2023-02-27 17:00
>The current recommendation is to use M-x company-complete (to set up a binding for it).

I don't think I can bind company-complete to tab or enter because it will create problems elsewhere. Even
if I could, when typing  `elj` I wouldn't know if it's a valid snippet until the completion does not happen.

>Is that not comfortable enough for you? 

The problem is I would have to bind company-complete to tab and enter which would create problems.

>Do you type out snippet names in full often during completion?

Yes because a lot of my snippets are two or three letter words. If I had to do a completion on `elp`
In the current setup I would have to type `el` then go though all the snippets `el, elP, ela,elb....` till I get to `elp`.

![current](https://i.imgur.com/pvpB84c.png)

With that patch it's much faster, all I have to do is `elp` tab/enter. I know `elp` is a valid snippet because
the completion window pops up.

![patch](https://i.imgur.com/aNxOYdM.png)

Thanks

**Comment by dgutov** [comment] 2023-02-27 22:51
> I don't think I can bind company-complete to tab or enter because it will create problems elsewhere.

I use a totally different binding for that: `C-/`. But `tab` would be handier for sure.

> Even
if I could, when typing elj I wouldn't know if it's a valid snippet until the completion does not happen.

Fair enough.

> With that patch it's much faster, all I have to do is elp tab/enter. I know elp is a valid snippet because
the completion window pops up.

Very good. I'll a little wary of potential misfires for this feature, but only using it for snippets seems like a safe choice.

We can add an option later, if it turns out people want this behavior in more cases.

**Comment by rickalex21** [comment] 2023-02-28 00:21
Sounds good. Thanks.

**Comment by dgutov** [comment] 2023-02-28 01:11
Pushed to master.
