### ISSUE TITLE
Filtering the result of 'company-filter-candidates' (nesting) ?

### ISSUE THREAD

**Issue by Antoine-Patel** [company-mode/company-mode#411] opened 2015-10-05 19:42 UTC
I filter completion candidates a lot (`company-filter-candidates`). Sometimes I would like to filter some more the already filtered candidates list, for example when it's still too big. Is it possible ? 

It seems triggering `company-filter-candidates`, while already filtering candidates, resets the filter string (search string). I tried to use `company-search-candidates` while filtering, to achieve a similar effect, but it doesn't work.

The most problematic is: I never know if I can filter "early" and get a limited filtered candidates list, or have to go "the long way" preemptively in order to make sure I won't get a huge list. Because if it does happen, I have to cancel the filtering, then somewhat do something else (possibly before re-doing the filtering...), which almost always ends up being much slower and painful than it should.

That, or I'm missing the "right" thing to do when filtering did not narrow the candidates list enough.

**Comment by dgutov** [comment] 2015-10-06 04:48
This might be a duplicate of #313, which I have unfortunately still haven't gotten around to.

Would that kind of flexible matching satisfy you as well?

**Comment by Antoine-Patel** [comment] 2015-10-06 08:35
Yes, using space delimited words as a filter string to achieve the same result would be fine too, especially if the underlying implementation is less difficult.

I only looked at existing issues with "filter" in the title when trying to avoid making a duplicate, and I didn't know Ido, so I missed #313. But this issue is a duplicate.

**Closed** 2015-10-07 03:14 UTC
Labels: duplicate

**Comment by dgutov** [comment] 2015-10-07 03:15
You can try it out now.

**Comment by Antoine-Patel** [comment] 2015-10-07 13:31
I only played with it for a bit, but it seems to work great. Filtering is definitively more powerful and useful now.

However (I don't know if it was intentional or not) this new feature is a bit "hidden" and hard to find. At first I thought it was going to be the default behavior. When I saw it didn't worked out of the box, I looked up the documentation for `company-filter-candidates`, but couldn't find anything about it. Same for `company-search-candidates` (that is mentioned by `company-filter-candidates`). I had to check the commit `cec8779 ` diff view on github to know that I had to `(setq company-search-regexp-function 
      'company-search-words-in-any-order-regexp)`.

I'd suggest (It's ok if you don't agree):
- Having `company-search-regexp-function` be at least mentioned by `company-filter-candidates`'s docstring (and maybe `company-search-candidates`'s docstring too). 
- Having somewhere in some docstring something like (the exact wording to choose depends on where it will be put if it happens)
*`company-filter-candidates` can use space delimited words to limit candidates to the ones containing all those words (in the given order or in any order) by customizing `company-search-regexp-function` to use `company-search-words-in-any-order-regexp` (any order) or `company-search-words-regexp` (given order)*. 

Because in my opinion the docstring of `company-search-regexp-function` is not really clear to end users about the fact it can make `company-filter-candidates` awesome.

Now this comment sounds too much negative while all the docstrings stuff is a minor complain. Thanks a lot for fixing this issue. It will help me a lot to type less, an that's pretty vital when you occasionally have pains in the fingers/wrists/forearms like me.

**Comment by dgutov** [comment] 2015-10-08 11:55
> However (I don't know if it was intentional or not) this new feature is a bit "hidden" and hard to find.

Possibly. In the end, we don't have a manual, only docstrings, and it's not good to be too verbose in docstrings.

> Having company-search-regexp-function be at least mentioned by company-filter-candidates's docstring (and maybe company-search-candidates's docstring too).

I've added the mention in `company-search-candidates`. As you say `company-filter-candidates` already refers to it.

> Having somewhere in some docstring something like (the exact wording to choose depends on where it will be put if it happens)

That sounds like manual-level material. It would be great if someone would work on one. But alternatively, you can create a wiki page describing the Company search function in more detail.

> I had to check the commit cec8779 diff view on github

That's what I thought you would start with (after all, GitHub tells you which commit closed the issue). Another option would be to look inside NEWS.md.

**Comment by dgutov** [comment] 2015-10-08 12:02
> Thanks a lot for fixing this issue. It will help me a lot to type less, an that's pretty vital when you occasionally have pains in the fingers/wrists/forearms like me.

No problem! Hope you get better.
