### ISSUE TITLE
(error "Nothing to complete") when press <SPACE> when company active

### ISSUE THREAD

**Issue by seudut** [company-mode/company-mode#614] opened 2016-11-19 16:01 UTC
Today I updated all my emacs packages, I meet this error  in `emacs-lisp-mode`.
the scenario is, after I input `(defun`, the company is active, then I press `<SPACE>`,  I get the error below

```
Debugger entered--Lisp error: (error "Nothing to complete")
  signal(error ("Nothing to complete"))
  error("Nothing to complete")
  semantic-analyze-possible-completions(nil)
  semantic-analyze-completion-at-point-function()
  completion--capf-wrapper(semantic-analyze-completion-at-point-function optimist)
  run-hook-wrapped(completion--capf-wrapper semantic-analyze-completion-at-point-function optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company--force-sync(company-capf (prefix) company-capf)
  company--multi-backend-adapter((company-capf :with company-yasnippet) prefix)
  apply(company--multi-backend-adapter (company-capf :with company-yasnippet) prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) (company-capf :with company-yasnippet))
  company-call-backend(prefix)
  company--continue()
  company--perform()
  company-post-command()

```

The strange is that this error only happens if `lispy-goto-local` is called before as I tested.   `lispy-goto-local` is a `lispy-mode` function to go to the symbol in current file. Although I already defined `SPC` to nil

    (define-key company-active-map (kbd "SPC") nil)

but this looks doesn't work. 

While, if I have never called `lispy-goto-local`, the `company-mode` works well. so I created an issue for `lispy-mode`  <https://github.com/abo-abo/lispy/issues/313>.  I am still not very sure if it's lispy cause this issue or not.

What does this error message mean, and is there any workaround for `compayn-mode` to suppress this error ?

**Comment by dgutov** [comment] 2016-11-20 22:28
Looking at the backtrace, this does seem like a Lispy problem (it uses Semantic, and apparently leaves the buffer in a somewhat inconsistent state).

**Comment by seudut** [comment] 2016-11-21 03:47
Thanks.
Yes, I have done some investigation. it is indeed a semantic issue. and some lispy calls trigger  the semantic mode change.  After I disable semantic mode by call `semantic-mode`, this issue is gone.

I don't find what is `<SPACE>` mapping, but the issue occurs on pressing `<SPACE>` when company is active. As I don't want to disable `semantic-mode` globally,  I create a function and map it to `<SPACE>` in `company-active-mode` to workaround this issue

here is my solution, just FYI. Until now, it woks fine. 

```
(defun sd/company-stop-input-space ()
  "Stop completing and input a space,a workaround of a semantic issue `https://github.com/company-mode/company-mode/issues/614'"
  (interactive)
  (company-abort)
  (insert " "))

(define-key company-active-map (kbd "SPC") #'sd/company-stop-input-space)
```

**Comment by dgutov** [comment] 2016-11-21 09:12
> it is indeed a semantic issue

No, it's still a Lispy issue. At least until we get any evidence to the contrary.

> but the issue occurs on pressing <SPACE> when company is active.

That might be caused by `company-auto-complete` being t. Although I don't see why it wouldn't happen when you type just about any other character, triggering completion to start.

**Comment by seudut** [comment] 2016-11-21 10:31
Thanks @dgutov . I am not very sure if lispy has problem or not here.

I checked, `company-auto-complete` is `nil` in my case. `company-mode` is enabled globally, and the flag `company-global-modes` is `t`

do you have any idea to identify the issue more clearly?

**Comment by dgutov** [comment] 2016-11-21 18:05
Does using Lispy commands turn on some electric interaction? Because `SPC` is in `lispy-mode-map-special`.

**Comment by seudut** [comment] 2016-11-22 12:29
I have defined `SPC` as nil in `lispy-mode-map`, `(define-key lispy-mode-map (kbd "SPC") nil)`, but the issue still exist.

**Comment by dgutov** [comment] 2016-11-22 12:42
What if you bind it to `self-insert-command` there?

**Comment by seudut** [comment] 2016-11-22 12:48
yes, it already bind to `self-insert-command`

**Comment by dgutov** [comment] 2016-11-22 12:51
OK, let's wait for Lispy's author to weigh in, then.

**Comment by gdv** [comment] 2016-11-23 09:51
I have the same problem while editing a python file. The backtrace is:
```
  signal(error ("Nothing to complete"))
  error("Nothing to complete")
  semantic-analyze-possible-completions(nil)
  semantic-analyze-completion-at-point-function()
  completion--capf-wrapper(semantic-analyze-completion-at-point-function optimist)
  run-hook-wrapped(completion--capf-wrapper semantic-analyze-completion-at-point-function optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer build-red-blue-graph.py> #<window 3 on build-red-blue-graph.py> 344 1249)
  apply(company-idle-begin (#<buffer build-red-blue-graph.py> #<window 3 on build-red-blue-graph.py> 344 1249))
  timer-event-handler([t 22581 24681 759079 nil company-idle-begin (#<buffer build-red-blue-graph.py> #<window 3 on build-red-blue-graph.py> 344 1249) nil 939000])
```
Also, `company-auto-complete` is `nil`

**Comment by dgutov** [comment] 2016-11-23 09:58
When editing and pressing `SPC` or just editing?

**Comment by gdv** [comment] 2016-11-23 10:06
Only when pressing `SPC`

**Comment by seudut** [comment] 2016-11-23 16:27
Looks like, in my case, when pressing `C-e`, `C-a` also will trigger this error when company is active.

**Comment by dgutov** [comment] 2018-12-12 00:44
This might have been fixed in the meantime.

**Closed by dgutov** 2018-12-12 00:44 UTC
Labels: third party issue

**Comment by riccardomurri** [comment] 2019-01-30 09:49
I am still running into this issue in Python mode; exact same traceback as reported in https://github.com/company-mode/company-mode/issues/614#issuecomment-262471314 . Seems definitely due to a bad interaction with `semantic-mode`.

```
emacs-version: "25.2.2"
company-backends: (company-shell-env company-shell company-anaconda company-ansible company-bbdb company-nxml company-css company-semantic company-clang company-cmake company-capf company-files ...)
prog-mode-hook: (semantic-mode rmurri/turn-on-hs-minor-mode which-function-mode highlight-indentation-mode flycheck-mode turn-on-fci-mode)
python-mode-hook: (whitespace-cleanup-on-save untabify-buffer-on-save anaconda-eldoc-mode anaconda-mode auto-virtualenvwrapper-activate er/add-python-mode-expansions pylint-add-key-bindings pylint-add-menu-items)
```

**Comment by riccardomurri** [comment] 2019-01-30 11:14
It looks like `semantic-analyze-completion-at-point-function` likes to
signal errors in many circumstances that should probably be ignored:

```
Debugger entered--Lisp error: (error "Cannot find types for ‘\"Python\"’")
  signal(error ("Cannot find types for ‘\"Python\"’"))
  error("Cannot find types for ‘\"Python\"’")
  completion--capf-wrapper(semantic-analyze-completion-at-point-function optimist)
  run-hook-wrapped(completion--capf-wrapper semantic-analyze-completion-at-point-function optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-capf)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer install.py> #<window 182 on install.py> 11129 25762)
  apply(company-idle-begin (#<buffer install.py> #<window 182 on install.py> 11129 25762))
  timer-event-handler([t 23633 34259 574876 nil company-idle-begin (#<buffer install.py> #<window 182 on install.py> 11129 25762) nil 472000])
```

I guess the quick fix is to just disable `semantic-mode` but perhaps
those functions should be special-cased in `company-capf`?
