### ISSUE TITLE
Icons support

### ISSUE THREAD

**Issue by ema2159** [company-mode/company-mode#945] opened 2020-01-25 03:40 UTC
I know that company-box exists (although it's a little bit neglected), but is there any plans on adding optional icons support for company itself? Or that's something that is not in the plans neither mid nor long term?

**Comment by Sarcasm** [comment] 2020-01-25 10:48
I think this is a duplicate of https://github.com/company-mode/company-mode/issues/756.
Your title might be better though.
My understanding, is that this feature needs someone to implement it, and there are some questions to answer, such as how to make it compatible with capf.

**Comment by dgutov** [comment] 2020-01-25 21:15
Long-term, maybe. If I end up having to implement this myself.

Also, I'm not sure if SVG icons are feasible for use with an overlay-based popup. Meantime, we're currently working out performance/accuracy problems with child frames (and posftrame in particular).

I'm closing this issue, please feel free to continue the discussion in the existing one (I think its title is not worse).

**Closed by dgutov** 2020-01-25 21:15 UTC
Labels: duplicate

**Comment by ema2159** [comment] 2020-01-25 21:26
@dgutov ok, that's good to know! Maybe a good option would be to integrate all-the-icons instead to having to include additional SVG icons, just an idea.

**Comment by dgutov** [comment] 2020-01-25 21:53
That's an option, of course.
