### ISSUE TITLE
Provide letters and not digits as key bindings for completion of strings starting with digits

### ISSUE THREAD

**Issue by dbitouze** [company-mode/company-mode#250] opened 2014-12-08 09:28 UTC
Hi,

when I start to write numbers (strings consisting of digits only), for instance `2014`, the company popup appears after the first two digits, but typing the next digit leads to an undesirable completion, namely (in my current case as shown in the joined image) `2000`. Hence, if I type the last two digits `14`, I end up with the wrong number `20004` instead of `2014`.

Hence, for strings that start with digits, I suggest to provide letters and not digits as key bindings for completion.

Okay, still strings mixing letters and digits would be problematic but these are 
likely to be less common than not mixing strings.

Best regards.

![completion1](https://cloud.githubusercontent.com/assets/1032633/5337084/c474ad2c-7ec4-11e4-9743-e8937501daa7.png)

**Comment by azzamsa** [comment] 2018-06-10 04:34
If I understand correctly. Is this issue discussing about 'accessing `company-complete-number` without M-num', but using only numbers ?

I come here to ask this feature too. It would be nice to have toggle for activating this feature. 

The problem is: company will confuse if the candidates contains number. But it seems abo-abo had [a fix](https://github.com/abo-abo/oremacs/blob/d5c4a24fce16082e0897af5681176baccd42593e/modes/ora-company.el#L22)

**Comment by dgutov** [comment] 2021-05-17 17:25
The issue referenced above was #188, which is like a more general version of this request (but that would probably depend on a particular implementation). So I'm going to close this now, but people should feel free to copy the snippet above to some wiki page.

**Comment by dgutov** [comment] 2021-05-17 17:26
The snippet from this comment, I mean: https://github.com/company-mode/company-mode/issues/250#issuecomment-66101707

**Closed by dgutov** 2021-05-17 17:25 UTC
Labels: wishlist
