### ISSUE TITLE
Releasing an updated version of company-mode on MELPA stable

### ISSUE THREAD

**Issue by sixpointzero** [company-mode/company-mode#542] opened 2016-06-16 14:10 UTC
The company-mode package on [MELPA stable](https://stable.melpa.org/) is quite old (at v0.8.12). Please consider releasing an updated version of company-mode on MELPA stable.

**Comment by dgutov** [comment] 2016-06-19 23:44
Duplicate of https://github.com/company-mode/company-mode/issues/498

**Closed by dgutov** 2016-06-19 23:44 UTC
