### ISSUE TITLE
Enable inside symbols?

### ISSUE THREAD

**Issue by vspinu** [company-mode/company-mode#340] opened 2015-04-09 19:39 UTC
I have gone through all custom vars twice now and I still don't see the way to enable tooltip in the middle of the symbol. So if I am inside "sym|bol" I still want the completion for "symptoms" to pop up.

**Comment by dgutov** [comment] 2015-04-10 01:32
Indeed, we can't do that, thus entirely side-stepping issues like https://github.com/auto-complete/auto-complete/pull/50

I'm keeping this shortcoming in mind, but also note how nobody's asked about it since https://github.com/company-mode/company-mode/issues/53.

**Comment by vspinu** [comment] 2015-04-10 09:09
I definitely would like to have auto-complete/auto-complete#50 enabled. 

I often change and move stuff in my code, so being in the middle of the symbol happens pretty often which leads to a lot of uncomfortable disruptions. Each time it's something along the following lines: my brain expects a popup, but it never comes (this takes a second or so.); then insert a space, come back and delete previous char and type that char again to trigger the popup (another 3-4 seconds).

**Comment by cslux** [comment] 2015-04-10 11:23
+1

**Comment by egarrulo** [comment] 2015-06-30 14:06
Another vote.

Dmitry, my understanding is that such a feature would be too complex to implement while matching everyone's peculiar preferences.  Then, would you please tell us where Company decides that it is inside a symbol and thus not complete, so that we can patch Company on our own?  I have looked into the source code but I haven't been able to determine it.

Anyway, below is a snippet of code to insert a space and start completion with current Company, to solve the case mentioned by Vspinu:

    (defun insert-space-and-company-complete ()
      (interactive)
      (save-excursion
        (insert " "))
      (company-complete))

**Comment by vspinu** [comment] 2015-06-30 14:26
I think this is decided in the source prefix matcher. Sources that I have built all complete within symbol.

**Comment by dgutov** [comment] 2015-06-30 14:40
Yup. To fix that across the board, will require a change in the API.

**Comment by egarrulo** [comment] 2015-06-30 14:51
Mmm... What workaround could be devised, then, to make the text after point invisible to backends?  Maybe copying the prefix in a temporary buffer with the same major mode?

**Comment by egarrulo** [comment] 2015-06-30 15:00
Or -- more easily -- by inserting some text before triggering completion and then deleting such text in `company-completion-finished-hook`?

**Comment by dgutov** [comment] 2015-06-30 15:01
If you're intend on doing a workaround, try temporarily removing the part of the symbol after point. You can even restore it immediately after the `prefix` call returns.

**Comment by valentjedi** [comment] 2017-11-04 15:38
A bit of necrobumping here - I would love to see it someday :) I'm not confident enough to contribute it myself though.

**Comment by zk-phi** [comment] 2020-11-30 12:46
I've worked around this with my fork https://github.com/zk-phi/company-mode (note that this is not well-tested and may lead to unexpected behaviors).

![hoge 21 22 56](https://user-images.githubusercontent.com/3530521/100611814-418e1780-3355-11eb-9799-a23d26279fdf.gif)

**Comment by yugaego** [comment] 2021-09-17 04:48
It seems to me this topic can be split into the two (maybe more?) types.

Let's say we have a candidate "Foobar".
*First type*
"Foo|remove-it" completes to "Foobar".

*Second type*
 "Foo|keep-it" completes to "Foobar keep-it".

It is not always clear to which of these types a comment/request belongs.
So I wonder what were the exact use-cases people had but didn't describe.

I personally have, so far, only needed and was used to (probably other editors habit) to the second type.
I suppose it can be resolved based on [workaround suggested earlier](https://github.com/company-mode/company-mode/issues/340#issuecomment-117198888).
For example, the following should work fine (need more time testing) for my current setup, heavily influenced by https://github.com/company-mode/company-mode/issues/1116:

```elisp
 (setq
   company-minimum-prefix-length 1
   company-idle-delay 0
   company-tooltip-idle-delay 10        ; Enable tooltip manually
   company-frontends '(company-pseudo-tooltip-unless-just-one-frontend-with-delay
                       company-preview-frontend
                       company-echo-metadata-frontend))

  (global-set-key (kbd "C-c c")
                  (lambda ()
                    (interactive)
                    (let ((company-tooltip-idle-delay 0.0))
                      (if (looking-at "\\S-")
                          (save-excursion (insert " ")))
                      (company-complete)
                      (and company-candidates
                           (company-call-frontends 'post-command)))))
```

Back to the first type, maybe the next step (other than evaluating the potential user-base) could be reviewing/testing [the changes @zk-phi mentioned](https://github.com/company-mode/company-mode/compare/master...zk-phi:master)?

**Comment by zk-phi** [comment] 2021-12-13 09:14
I agree with that, we usually want "Second type" behavior in most cases.

Actually, my patch above works like that by default.

`|baz` -> `Foo|baz` -> `Foo|bar]baz` (suggested) -> `Foobar|baz` (completed)

It auto-deletes characters if and only if there will be a repetition when completed.

`|arbaz` -> `Foo|arbaz` -> `Foo|bar]arbaz` (suggested) -> `Foobar|baz` (repeated `ar` is merged after completion)

I don't think that the auto-delete behavior is necessary, but it's useful in some cases and nice to have as an option.

---

FYI: I now extracted the patch as a separate package and is now easier to try.

https://github.com/zk-phi/company-anywhere

**Comment by seagle0128** [comment] 2022-04-08 10:49
The [patch](https://github.com/zk-phi/company-anywhere) from @zk-phi works well for me. IMO the best behaviors should be like [corfu](https://github.com/minad/corfu).

**Comment by mguzmann** [comment] 2022-11-09 19:23
For company-files I wish the behavior was the first type

* `third-folder/the-file.txt` -> `"./some-folder/some-|other-folder/some-file.txt"` - > `"./some-folder/some-thir-folder/the-file.txt"`

I feel this is a case where keeping the suffix doesn't make much sense.

**Comment by dgutov** [comment] 2024-06-06 02:31
Here's WIP: https://github.com/company-mode/company-mode/pull/1474

**Closed** 2024-07-13 03:03 UTC
Labels: wishlist
