### ISSUE TITLE
args-out-of-range error in different modes

### ISSUE THREAD

**Issue by welf** [company-mode/company-mode#667] opened 2017-05-16 01:23 UTC
When I work in Emacs with .hs files all works fine. But when I load my file in intero repl, start printing function name and, when autocomplete suggests anything, I hit backspace and always get an error: 
```
Debugger entered--Lisp error: (args-out-of-range #<buffer *intero:global-project::repl*> 588 589)
  buffer-substring-no-properties(588 589)
  company--continue()
  company--perform()
  company-post-command()
```

Steps to reproduce: 

1. Open any .hs file
2. Load it to [intero](https://github.com/commercialhaskell/intero) REPL 
3. Start printing any function name and wait until autocomplete suggests you a completion variant. 
4. Hit backspace button and get an error. 

I thought it was an intero bug, but I've got today the same error working in .org file in org-mode. Steps to reproduce are the same, but without loading files to repl - when the autocomplete suggests you a completion variant and you hit the backspace button, you get the same error. 

MacOS Sierra 10.12.14
Emacs 25.2 (9.0)
company-20170420.1837

The output of `M-x company-diag`: 
```Emacs 25.2.1 (x86_64-apple-darwin16.5.0) of 2017-04-26 on MBPro-AW.station
Company 0.9.3

company-backends: (intero-company
 (company-capf company-dabbrev-code)
 company-dabbrev)

Used backend: company-dabbrev
Prefix: ""
Completions:
  "logo"
  "28576"
  "staff"
  "xterm"
  "init"
  ... _and 11450 other completions_
  "ghci"
  "stack"
  "starting"
```

**Comment by dgutov** [comment] 2017-05-16 23:20
> I've got today the same error working in .org file in org-mode

Can't reproduce.

Please provide the exact steps: what should the buffer contents be, for instance.

**Comment by welf** [comment] 2017-05-17 17:58
It doesn't depend on the buffer contents. Here is the screencast: 

![company-intero](https://cloud.githubusercontent.com/assets/1454462/26168664/39a6962a-3b3b-11e7-88da-f9802a37b23e.gif)

**Comment by dgutov** [comment] 2017-05-17 18:05
Can you reproduce that with Org?

I'd rather not have to install the Haskell ecosystem to try this out.

**Comment by dgutov** [comment] 2017-05-17 18:07
Never mind, reproduced it in IELM.

Thanks!

**Comment by welf** [comment] 2017-05-17 18:12
The same error I get while working in org-mode: 

![company-org-mode](https://cloud.githubusercontent.com/assets/1454462/26169216/282fd9ae-3b3d-11e7-815e-91a0c1704148.gif)

**Comment by welf** [comment] 2017-05-17 18:23
It seems that the error is thrown when after backspacing it remains only one letter of the suggested completion. 

And (at least in org-mode) the error doesn't appear when there is another line with text after the point: 

![company-org-mode2](https://cloud.githubusercontent.com/assets/1454462/26169610/b28c2d54-3b3e-11e7-92a0-93e85e2f7ecc.gif)

Hope it helps.

**Comment by welf** [comment] 2017-05-17 18:50
And I don't know whether it is the same error with `shell` (as well as with `eshell` and `term`): 

![company-shell](https://cloud.githubusercontent.com/assets/1454462/26170567/302a9392-3b42-11e7-892c-9140d8ad902c.gif)

The Backtrace message: 
```
Debugger entered--Lisp error: (file-error "Opening directory" "Not a directory" "/usr/local/bin/magick")
  file-name-all-completions("s" "/usr/local/bin/magick/")
  shell--command-completion-data()
  shell-command-completion()
  run-hook-with-args-until-success(shell-command-completion)
  comint-completion-at-point()
  completion--capf-wrapper(comint-completion-at-point optimist)
  run-hook-wrapped(completion--capf-wrapper comint-completion-at-point optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company--force-sync(company-capf (prefix) company-capf)
  company--multi-backend-adapter((company-capf company-dabbrev-code) prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *shell*> #<window 8 on *shell*> 9 12)
  apply(company-idle-begin (#<buffer *shell*> #<window 8 on *shell*> 9 12))
  timer-event-handler([t 22812 39420 606872 nil company-idle-begin (#<buffer *shell*> #<window 8 on *shell*> 9 12) nil 0])
```

The output of `company-diag` after the error:
```
Emacs 25.2.1 (x86_64-apple-darwin16.5.0) of 2017-04-26 on MBPro-AW.station
Company 0.9.3

company-backends: ((company-capf company-dabbrev-code)
 company-dabbrev)

Used backend: company-dabbrev
Prefix: nil
Completions: none
```

**Comment by dgutov** [comment] 2017-05-17 21:38
The original problem should be fixed now, thanks for the report.

**Closed** 2017-05-17 21:38 UTC

**Comment by dgutov** [comment] 2017-05-17 21:40
Regarding completion in `shell` and friends, I cannot reproduce. But it might be a bug in Emacs.

If you disable `company-mode`, can you reproduce the error with `C-M-i`? If so, please `M-x report-emacs-bug`.

**Comment by welf** [comment] 2017-05-18 10:42
You are right, with `company-mode` disabled, I can reproduce it with `completion-at-point`. Will report the emacs bug. It seems it searches for a file with completions in my PATH (`/usr/local/bin/magick/` is the last entry in my PATH) and after it finds nothing, raises the error. 

Thank you!

**Comment by dgutov** [comment] 2017-05-18 10:47
I think it complains that the last entry in your PATH is not a directory.

Maybe it should ignore that, but this way, the user has a chance to fix the value.

**Comment by welf** [comment] 2017-05-18 12:38
Thank you! I just noticed it where in my path 3 paths to files, not to directories. Fixed it and it works now! 👍

**Comment by stardiviner** [comment] 2017-05-19 02:57
@welf How do you fontify that Org headline like that?

**Comment by welf** [comment] 2017-05-19 13:04
@stardiviner  I use [`org-bullets` mode](https://github.com/sabof/org-bullets) and [`org-beautify-theme`](https://github.com/jonnay/org-beautify-theme).

**Comment by stardiviner** [comment] 2017-05-20 03:20
@welf I have not found the symbol which used in your `org-bullets` in your `.emacs.d` repository.

**Comment by welf** [comment] 2017-05-22 14:39
@stardiviner Symbols you see depend on theme you use. I use `flatui` theme and `org-bullets` takes symbols from there. For example, in `solarized-light` theme you'll get such symbols:
<img width="453" alt="solarized" src="https://cloud.githubusercontent.com/assets/1454462/26313949/ba7b8d1c-3f0c-11e7-9c7a-3d2246a9d231.png">

My `.emacs.d` repository is heavily outdated because I am currently experimenting a lot and rewrite my Emacs configuration with literate programming in `org-mode`.
