### ISSUE TITLE
Company-mode menu breaks the comment background face

### ISSUE THREAD

**Issue by isolet** [company-mode/company-mode#514] opened 2016-05-18 09:32 UTC
Hi,

I find that the company-mode popup menu will break the comment background. Please see the differences below.

![](https://cloud.githubusercontent.com/assets/5475262/15347348/7825034e-1cf3-11e6-8a19-278b09255376.png)
![](https://camo.githubusercontent.com/af5ce6fd6797ea0ab39d327c2411a0049c98a545/68747470733a2f2f73736c2e6d6f6566712e636f6d2f696d616765732f323031362f30352f31382f64626564646635316264346535393230323933336361363238646634383330612e706e67)

Is this a company-mode issue ? Is preventing this possible ? Thanks !  #https://github.com/syl20bnr/spacemacs/issues/6075

**Comment by dgutov** [comment] 2016-05-30 23:13
Yes, it's our fault, and it's rather hard to do better with overlay-based popup rendering.

Let's call this a duplicate of #71.

**Closed by dgutov** 2016-05-30 23:13 UTC
