### ISSUE TITLE
`company-capf` incorrectly completes when Eshell is in the command position

### ISSUE THREAD

**Issue by ethan-leba** [company-mode/company-mode#1322] opened 2022-04-24 16:02 UTC
#### Describe the issue
When completing in the command position of Eshell, the completions will only list the most current segment of the path, but selecting the completion will replace the entire path.

#### Steps to reproduce
1. Open `eshell`
2. Type in `/bin/ki`
3. Press `RET` to company-complete it

#### Expected behavior
Expected completion to replace only the current segment of path.

#### `M-x company-diag` output

```
Emacs 28.1 (aarch64-apple-darwin21.3.0) of 2022-04-10 on MacBook-Pro.attlocal.net
Company 0.9.13

company-backends: (company-capf)

Used backend: company-capf
Value of c-a-p-f: (pcomplete-completions-at-point t)
Major mode: eshell-mode
Prefix: "/bin/ki"
Completions:
  #("kill" 0 4 (face (completions-common-part)))
```

#### Screenshots
<img width="114" alt="Screen Shot 2022-04-19 at 4 08 20 PM" src="https://user-images.githubusercontent.com/4625599/164985268-6b36ce45-aa3d-4c06-95a3-385b31802d3c.png">
<img width="114" alt="Screen Shot 2022-04-19 at 4 08 25 PM" src="https://user-images.githubusercontent.com/4625599/164985267-6f20ef9e-9b34-4968-94e0-3466e5499c0b.png">

**Comment by dgutov** [comment] 2022-04-27 20:39
Yes. Looks like it happens with the default completion at well.

`C-M-i` is bound to a different command in `eshell-mode`, but if you type `/bin/` in eshell, follow it with `M-x completion-at-point` twice and then pick a completion in the displayed buffer, you will see the same result.

The next step is `M-x report-emacs-bug`. :shrug:

**Comment by minad** [comment] 2022-05-01 09:04
Found it! The issue was actually reported to Swiper a long time ago.

Swiper issue: https://github.com/abo-abo/swiper/issues/2879
Emacs upstream issue: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=48995

**Comment by dgutov** [comment] 2022-05-01 21:37
Thanks! I pinged the bug report. Though that's no guarantee of seeing it fixed, of course.

**Comment by minad** [comment] 2022-05-01 21:44
It seems that this is an Emacs 28 regression, so it should be fixed even on that branch.

**Comment by dgutov** [comment] 2022-05-01 22:13
Seems so. Though it's rather late for Emacs 28.1.

**Comment by ethan-leba** [comment] 2022-05-02 03:12
Thanks for pinging the bug report! For anyone else running into this issue who's looking for a short term fix, putting the following in your config will do the trick, which is essentially reverting[ the commit which introduced the bug](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=82c76e3aeb2465d1d1e66eae5db13ba53e38ed84):

```
(defun eshell--complete-commands-list ()
  "Generate list of applicable, visible commands."
  (let ((filename (pcomplete-arg)) glob-name)
    (if (file-name-directory filename)
        (if eshell-force-execution
            (pcomplete-dirs-or-entries nil #'file-readable-p)
          (pcomplete-executables))
      (if (and (> (length filename) 0)
               (eq (aref filename 0) eshell-explicit-command-char))
          (setq filename (substring filename 1)
                pcomplete-stub filename
                glob-name t))
      (let* ((paths (eshell-get-path))
             (cwd (file-name-as-directory
                   (expand-file-name default-directory)))
             (path "") (comps-in-path ())
             (file "") (filepath "") (completions ()))
        ;; Go thru each path in the search path, finding completions.
        (while paths
          (setq path (file-name-as-directory
                      (expand-file-name (or (car paths) ".")))
                comps-in-path
                (and (file-accessible-directory-p path)
                     (file-name-all-completions filename path)))
          ;; Go thru each completion found, to see whether it should
          ;; be used.
          (while comps-in-path
            (setq file (car comps-in-path)
                  filepath (concat path file))
            (if (and (not (member file completions)) ;
                     (or (string-equal path cwd)
                         (not (file-directory-p filepath)))
                     (if eshell-force-execution
                         (file-readable-p filepath)
                       (file-executable-p filepath)))
                (setq completions (cons file completions)))
            (setq comps-in-path (cdr comps-in-path)))
          (setq paths (cdr paths)))
        ;; Add aliases which are currently visible, and Lisp functions.
        (pcomplete-uniquify-list
         (if glob-name
             completions
           (setq completions
                 (append (if (fboundp 'eshell-alias-completions)
                             (eshell-alias-completions filename))
                         (eshell-winnow-list
                          (mapcar
                           (lambda (name)
                             (substring name 7))
                           (all-completions (concat "eshell/" filename)
                                            obarray #'functionp))
                          nil '(eshell-find-alias-function))
                         completions))
           (append (and (or eshell-show-lisp-completions
                            (and eshell-show-lisp-alternatives
                                 (null completions)))
                        (all-completions filename obarray #'functionp))
                   completions)))))))
```

**Comment by mpereira** [comment] 2022-09-18 13:30
@ethan-leba works great, thank you! This has been bugging me for so long.

**Comment by stardiviner** [comment] 2022-10-01 01:43
@ethan-leba It works for me too. Thanks

**Comment by dgutov** [comment] 2023-01-08 21:58
Looks like it's fixed in Emacs 29.

**Closed** 2023-09-29 23:22 UTC
Labels: third party issue
