### ISSUE TITLE
The tooltip scrollbar alignment is broken on the candidate includes `…` character

### ISSUE THREAD

**Issue by templateK** [company-mode/company-mode#1388] opened 2023-06-21 09:38 UTC
#### Output of the command `M-x company-diag`
Emacs 28.2 (x86_64-apple-darwin18.6.0) of 2022-10-17 on foo-iMac
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (eglot-completion-at-point t)
Major mode: rust-mode
Prefix: stop
Completions: none

#### Describe the issue

The tooltip scrollbar alignment is broken on the candidate includes `…` character 
when `set-language-environment`  is set to CJK environment.

#### Steps to reproduce
1. install/setup rust-analyzer, make new rust project.

2. start `emacs -q` and  evaluate a buffer with following elisp code.
```elisp
(package-initialize)
(require 'use-package)
(use-package company :config (global-company-mode))
(use-package eglot)
(use-package rust-mode :config (add-hook 'rust-mode-hook 'eglot-ensure))
(set-language-environment "Chinese-BIG5")
```

3. try auto complete with following rust code.
```rust
fn main() {
    let s = String::new();
    s.
}
```

#### Expected behavior
The scrollabr should align.

#### Screenshots

On default language environment.
![company_default](https://github.com/company-mode/company-mode/assets/3207776/690b8d8e-4dcc-4dd3-9cd9-bafbfa7d7b48)

On Chinese-BIG5/Japanese/Korean language environment.
![company_cjk](https://github.com/company-mode/company-mode/assets/3207776/15d7bc86-3918-4357-8f0f-0003b8c1356a)

#### Additional context
Add any other relevant information here.

**Comment by templateK** [comment] 2023-06-29 19:04
@dgutov Is this issue will be addressed?

**Comment by templateK** [comment] 2023-06-30 11:46
I assume this issue won't be address as there's no response from the project owner and I found a workaround what I think not a solid one. so closing this issue. Feel free reopen this issue whenever you have a time for this.

**Comment by dgutov** [comment] 2023-06-30 23:58
Hi! It will need some investigation, possible with someone who understands the multi-language environment in Emacs better.

But perhaps there are some easier solutions as well.

In your testing, does `(company--clean-string "…")` when the environment is Chinese from when it is English?

**Comment by dgutov** [comment] 2023-07-01 00:08
I don't have RLS installed, so if you have a simple reproduction available, that could help speed this up.

**Comment by templateK** [comment] 2023-07-01 03:20
Thank you for responding to this issue.
<br>

> In your testing, does `(length (company--clean-string "…"))` return different values when the environment is Chinese from when it is English?

Yes, the evaluation result is `2` in CJK language-environment and `1` on default or English environment.
<br>

> I don't have RLS installed, so if you have a simple reproduction available, that could help speed this up.

 Below code can reproduce the issue without language server setup on `emacs -q`

```elisp
(defun mock-candidates (r)
  (list '("foo" "bar" "wat"
          "max(…) (as Ord)" "as_str()" "capacity()"
          "한글" "as_str()" "capacity()"
          "にほんご" "as_str()" "capacity()"
          "大五碼" "as_str()" "capacity()"
          "foo" "bar" "wat")))
(package-initialize)
(require 'use-package)
(use-package company 
 :config 
 (global-company-mode)
 (advice-add 'company-update-candidates :filter-args 'mock-candidates))
 
(set-language-environment "Chinese-BIG5")
;;(set-language-environment "Korean")
;;(set-language-environment "Japanese")

(global-set-key (kbd "C-e") 'company-complete)
```

**Comment by dgutov** [comment] 2023-07-02 02:55
Thanks, that repros. Hmm, but this is the weird part: `(string-width "大")` predictably returns 2 because the character is displayed wider than 1 column. But `…` is still 1 column wide.

So the problem with hiragana/katakana chars is expected: the rendered doesn't deal with fractional widths, the chars are simply treated as double width, so some extra padding is not added, and the line is narrower than is should have been.

But `(string-width "…")` reporting 2 doesn't seem to correspond to any meaningful reality (the char is no wider than A-Z ones, at least in my main font). Could be a bug in the "Chinese-BIG5" lang environment settings. I'll try to clear that up in the core bug tracker.

**Comment by templateK** [comment] 2023-07-02 11:18
I don't understand why the length of `…` is 2 on CJK environment on emacs either.  

The character rendered as 1 width character on every software including emacs regardless with proportional or mono spaced font in my experience.

**Comment by dgutov** [comment] 2023-07-02 12:59
https://debbugs.gnu.org/64420

**Comment by templateK** [comment] 2023-07-02 23:49
The `string-width` is guaranteed for terminal, but it doesn't make sense to me it returns 2 column width for the `…`.
Anyway, I think that will be separate emacs upstream issue.

If i evaluate `(company--string-width "…")`, Indeed it returns correct width. 

```elisp
(defun company--string-width (str)
   (if (display-graphic-p)
       (ceiling (/ (string-pixel-width str)
                   (float (default-font-width))))
     (string-width str)))
```

So, I tried to use this function with replacing all of the `string-width` with `company--string-width` inside `company.el`,
but an error occurs with following message.

> Company: An error occurred in post-command
> Company: frontend company-pseudo-tooltip-frontend error "Args out of range: 0, 20" on command post-command

I tracked down where the error happens, but I don't know how to proceed.  https://github.com/company-mode/company-mode/blob/b2df4b680aacc4534d60b79c871d0e4c37137d41/company.el#L3128

**Comment by dgutov** [comment] 2023-07-03 02:22
This is where I'm stuck too. The issue, I think, is that the new function defines a property that is not "additive" (a concatenation of strings doesn't necessarily get a sum of widths).

We can rewrite it to count char-by-char to retain that property, but then we also lose the benefit of "smoothing out" spans of characters with fractional widths, and the result will be a little slower as well (though probably not noticeably). The alternative is to try to make the additive property unnecessary (somewhere earler in the code than the place you found). I'm currently looking into that.

**Comment by dgutov** [comment] 2023-07-07 02:10
Hi! I've pushed an experimental change, check it out.

It has two parts:
1. Incorporating `company--string-width` and adjusting the expectations of the code around it. Probably used it in too many places; can revisit later.
2. Additional adjustment of popup line width for completions with fractional width (like the hiragana and kanji strings from your example).

Does 2. look valuable enough to be worth the added complexity? I haven't found a way to nail down the line height the same way yet: so any popup with these chars still looks "jumpy" to me when showing or scrolling. Though I suppose if someone manages to configure the main font to include these chars with the regular dimensions (height, at least), that wouldn't be an issue.

This second part actually seems to work in terminal Emacs too, not just GUI. That was a surprise.

**Comment by dgutov** [comment] 2023-07-07 02:10
Branch `cjk-string-width`.

**Comment by templateK** [comment] 2023-07-07 07:59
It almost works. Here's my test result.

The the position of the text of the buffer around the popup will change when the popup width changes
if the text of the buffer is CJK characters.

https://github.com/company-mode/company-mode/assets/3207776/5e747ef1-03ab-4742-804f-a0ff7777dd8a

```elisp
(defun mock-candidates (r)
  (list '("foo" "bar" "wat"
          "max(…) (as Ord)" "as_str()" "capacity()"
          "한한한한한한한글" "as_str()" "capacity()"
          "한한한한한한글" "as_str()" "capacity()"
          "한한한한한글" "as_str()" "capacity()"
          "한한한한글" "as_str()" "capacity()"
          "한한한한" "as_str()" "capacity()"
          "한한한" "as_str()" "capacity()"
          "한한" "as_str()" "capacity()"
          "한" "as_str()" "capacity()"
          "にほんご" "as_str()" "capacity()"
          "大五碼" "as_str()" "capacity()"
          "foo" "bar" "wat")))
```
<br>

> Does 2. look valuable enough to be worth the added complexity?

If you willing to tackle display problem of whole CJK character on company-mode, it's certainly worth the complexity in my opinion.
<br>

> I haven't found a way to nail down the line height the same way yet: so any popup with these chars still looks "jumpy" to me when showing or scrolling.

As you guessed, it displays the height of candidates are aligned well with proper font, e.g.) [D2Coding](https://github.com/naver/d2codingfont/releases/download/VER1.3.2/D2Coding-Ver1.3.2-20180524.zip)
<br>

That aside, `string-pixel-width` doesn't exist in emacs-28.2, so I had to define it manually. I don't know why it's removed added again on newer emacs.
<br>

Finally, I think displaying whole CJK character properly is a separate issue, so I consider original issue has been resolved 
if the absence of `string-pixel-width` on emacs-28.2 is handled.

**Comment by dgutov** [comment] 2023-07-08 01:49
> If you willing to tackle display problem of whole CJK character on company-mode, it's certainly worth the complexity in my opinion.

I don't think we'll be able to make them perfect. E.g. having the popup hide cover a part of the character (from the underlying text) is probably not possible. So the question is whether the extra complexity is worth the improvement (even though the rendering can still look janky in certain cases).

I've added a new tweak on Eli's recommendation. Does it make the behavior appreciably better? Over here, the displacement is one column less, but it still happens for most lines (except the one with `...`).

> As you guessed, it displays the height of candidates are aligned well with proper font, e.g.) [D2Coding](https://github.com/naver/d2codingfont/releases/download/VER1.3.2/D2Coding-Ver1.3.2-20180524.zip)

Thanks. I haven't tried it yet. Does it make the heights fixed? But not widths, right?

> That aside, string-pixel-width doesn't exist in emacs-28.2, so I had to define it manually. I don't know why it's removed added again on newer emacs.

That's a good note. The function is new (it's not in Emacs 27 either, IIUC), so we'd need to backport it as well.

> Finally, I think displaying whole CJK character properly is a separate issue, so I consider original issue has been resolved
if the absence of string-pixel-width on emacs-28.2 is handled.

Very good. Let's first see how far we can improve it with moderate effort, though.

**Comment by dgutov** [comment] 2023-07-08 22:03
Its seems like, out of the chars from the example, D2Coding is only missing `"大五碼"`.

**Comment by templateK** [comment] 2023-07-09 00:44
> I don't think we'll be able to make them perfect. E.g. having the popup hide cover a part of the character (from the underlying text) is probably not possible. So the question is whether the extra complexity is worth the improvement (even though the rendering can still look janky in certain cases).

Ah, I see. I still think it's worth.  I tested https://github.com/company-mode/company-mode/commit/8a53285ca0eaa04cc795ebde4abeab1bc8465a83 without fractional width support and I thought that doesn't look good at all. and the performance is really good with fractional width support on my machine(macOS, haswell CPU) after I backported [`string-pixel-width`](https://github.com/emacs-mirror/emacs/blob/afa4fa17232a806907e975c9532bdf12bb3e6c4c/lisp/emacs-lisp/subr-x.el#L332) and [`buffer-text-pixel-size`](https://github.com/emacs-mirror/emacs/blob/afa4fa17232a806907e975c9532bdf12bb3e6c4c/src/xdisp.c#L11619) from emacs master branch.

Regarding hiding cover part of the characther,  Can we use child frame for popup instead overlay? 
I tested with [company-posframe](https://github.com/tumashu/company-posframe) package. It worked well without any problem.

```elisp
(use-package posframe)
(use-package company-posframe :config (company-posframe-mode +1))
```
<br>


>Thanks. I haven't tried it yet. Does it make the heights fixed? But not widths, right?

Yes
<br>

> Its seems like, out of the chars from the example, D2Coding (tried it now) is only missing "大五碼".

Try below font setup

#### Installing CJK font
Use one of the options.

1. CJK Super font: [Noto Sans Mono CJK Super OTC](https://github.com/googlefonts/noto-cjk/raw/main/Sans/SuperOTC/NotoSansCJK.ttc.zip)

      Requirements
        - Linux that uses fontconfig and FreeType Version 2.5.0.1 or later
        -  macOS 10.8  or later
        - Windows 10 1607 or later

2. Individual CJK fonts.
[Traditional Chinese — Hong Kong (繁體中文—香港) | Mono Regular + Mono Bold](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/15_NotoSansMonoCJKhk.zip)
[Japanese (日本語) | Mono Regular + Mono Bold](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/11_NotoSansMonoCJKjp.zip)
[Korean (한국어) | Mono Regular + Mono Bold](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/12_NotoSansMonoCJKkr.zip)

#### Font configuration
```elisp
(set-face-attribute 'default nil :family "Noto Sans Mono CJK SC" :height 220)
(set-fontset-font (face-attribute 'default :fontset)
                  'big5 (font-spec :family "Noto Sans Mono CJK HK") nil nil)
(set-fontset-font (face-attribute 'default :fontset) 
                  'hangul (font-spec :family "Noto Sans Mono CJK KR") nil nil)
(set-fontset-font (face-attribute 'default :fontset) 
                  'japanese-jisx0208 (font-spec :family "Noto Sans Mono CJK JP") nil nil)
```
<br>

> Very good. Let's first see how far we can improve it with moderate effort, though.

Of course, I'll try my part.

**Comment by dgutov** [comment] 2023-07-10 02:12
> Try below font setup

Thanks, I'll try that sometime later. For now, D2Coding gives me a close enough approximation.

> I tested with [company-posframe](https://github.com/tumashu/company-posframe) package. It worked well without any problem.

Is there any reason you don't want to continue just using it?

IME it's a little glitchy on display (has to do with Emacs's handling of child frames under GNOME, I think; not much posframe's author can do), and a little slower when scrolling, but if it's not the case for you, it's a good idea to continue using it. Maybe we'll fold it in sometime in the future as an additional frontend, but that's a separate discussion.

posframe doesn't work on terminal either, so we need to keep a frontend that work there anyway. And while the overlay one is close to having all the same functionality, we can still tweak it for certain edge cases.

For example, it could be possible to "split" the fractional chars under the popup (on the right edge) by replacing them with a space of a suitable pixel width. That would still create a certain blinking effect in such cases, but over a small area and without moving the remainder of the line horizontally. Hopefully, it won't mess up some other odd cases too much.

Speaking of company-posframe, though, I think it also must have had the problem with `...` (the main issue in this report) before the first change in this branch. But it probably doesn't need the second one, or any subsequent tweaks (like the one described above).

**Comment by templateK** [comment] 2023-07-10 09:03
> Is there any reason you don't want to continue just using it?

I suggested child frame because I prefer out of the box support of such feature. Plus, I thought there might be benefits from tight integration such as simplification of code and performance enhancement compared to relying on external module when using child frame for popup. I don't have any opposition to using pos-frame.
<br>

> IME it's a little glitchy on display (has to do with Emacs's handling of child frames under GNOME, I think; not much posframe's author can do), 

That's bummer. Fair enough not to consider using child frame.
<br>

>Maybe we'll fold it in sometime in the future as an additional frontend, but that's a separate discussion.

If using child frame means implementing another company frontend module, I agree that implementing such frontend
is out of scope of this discussion.
<br>

> "split" the fractional chars under the popup (on the right edge) by replacing them with a space of a suitable pixel width. That would still create a certain blinking effect in such cases, but over a small area and without moving the remainder of the line horizontally. 

If that's possible, I'm sure it will be usable enough.
<br>

Anyway, character width mismatch situation such as "…" on terminal can be mitigated changing `char-width-table` on `set-language-environment-hook`, but changing `character-width-table` is emacs global scope, so I'm not sure this is good idea or how to integrate this. What do you think? 
<br>

Just to be clear, I did some more testing including terminal(builtin/kitty/iterm2) environment on macOS.

#### company - 20230416.2034
|                                       |    GUI - overlay      |  GUI - frame        | Terminal   | 
|---------------------------------------|-----------------------|---------------------|------------|
|Is overlay alignment good              |    no                 |  no                 | no         |
|Is text moving when popup width changes|    yes                |  yes                | yes        |

#### company - cjk without fractional width support
|                                       |    GUI - overlay      |  GUI - frame        | Terminal   | 
|---------------------------------------|-----------------------|---------------------|------------|
|Is overlay alignment good              |    no                 |  no                 | no         |
|Is text moving when popup width changes|    yes                |  yes                | yes        |
 
#### company - cjk https://github.com/company-mode/company-mode/commit/87351c2c596b74bd249dbeb28a35e69789c1a440
|                                       |    GUI - overlay      |  GUI - frame        | Terminal   | 
|---------------------------------------|-----------------------|---------------------|------------|
|Is overlay alignment good              |    yes                |  yes                | *yes       |
|Is text moving when popup width changes|    yes                |  no                 | yes        |

*yes only if we correct `character-width-table` for characters such as "…"

<details>
  <summary>Screenshots</summary>

  #### company - 20230416.2034  / GUI - overlay 
![company-master_gui-overlay](https://github.com/company-mode/company-mode/assets/3207776/a81e0cb0-cee7-4250-8d1f-fd9959b30745)

  #### company - 20230416.2034  / GUI - frame 
![company_master_gui-frame](https://github.com/company-mode/company-mode/assets/3207776/6d121d88-aa04-47b8-ab55-97160be68240)

  #### company - 20230416.2034  / Terminal 
![company-master_terminal](https://github.com/company-mode/company-mode/assets/3207776/05d051d2-7bf1-4521-8643-3cbf87fcfe83)

  #### company - cjk without fractional width support  / GUI - overlay 
![company-cjk-without-fractional-overlay](https://github.com/company-mode/company-mode/assets/3207776/f9ccfe2a-9767-456e-8e78-a17334e0896b)

  #### company - cjk without fractional width support  / GUI - frame 
![company-cjk-without-fractional_frame](https://github.com/company-mode/company-mode/assets/3207776/c760f3a3-81b7-4f5c-9324-3124c6d3ee40)

  #### company - cjk without fractional width support  / Terminal 
![company-cjk-without-fractional_terminal](https://github.com/company-mode/company-mode/assets/3207776/d200667c-2b54-42ef-8ec6-12f4adf008df)

  #### company - cjk / GUI - overlay 
![company-cjk_gui-overlay](https://github.com/company-mode/company-mode/assets/3207776/84ae1b27-813f-4d7d-9697-48e1994251c7)

  #### company - cjk / GUI - frame 
![company-cjk_gui-frame](https://github.com/company-mode/company-mode/assets/3207776/7bd139d3-342c-4b1d-a421-c8b8a298caa1)

  #### company - cjk / Terminal - without `character-width-table` fix
![company-cjk-terminal-without-character-width-table-fix](https://github.com/company-mode/company-mode/assets/3207776/77415904-9015-4c74-a316-ffe6ee129f19)

  #### company - cjk / Terminal - with `character-width-table` fix 
![company-cjk_terminal_with-character-width-table-fix](https://github.com/company-mode/company-mode/assets/3207776/106e2369-86a0-4ddc-9522-51b1fae14368)

</details>

**Comment by dgutov** [comment] 2023-07-11 02:55
> Plus, I thought there might be benefits from tight integration such as simplification of code and performance enhancement compared to relying on external module when using child frame for popup. I don't have any opposition to using pos-frame.

I do think it's a fine alternative, and the author has been very helpful, but I don't see it as a full replacement so far. Everybody is welcome to use it, though. IIUC the glitches are only apparent with some desktop environments but not others.

> Anyway, character width mismatch situation such as "…" on terminal can be mitigated changing char-width-table on set-language-environment-hook, but changing character-width-table is emacs global scope, so I'm not sure this is good idea or how to integrate this.

That's something to consider. But I also found other problems related to this char (see the report on debbugs, latest messages), so we'll see what is the final recommendation going to be.

> Just to be clear, I did some more testing including terminal(builtin/kitty/iterm2) environment on macOS.

Thanks for the thorough testing.

Could you try the latest version I just pushed? I implements this idea which fractional spaces mentioned previously and actually seems to look okay, even on the terminal (though the problem with `…` is still there with `-nw`).

It will need a fair bit of testing, though, with different buffer contents, and, ideally, under different terminals as well. To iron out any problems with this whole new approach.

**Comment by templateK** [comment] 2023-07-11 23:38
I tested the https://github.com/company-mode/company-mode/commit/ec51f51b22d33bc28a5dc1c9e0aa785f9b425a37 as long as I can and saw no problem in GUI or terminal environment on macOS except the `…` problem on terminal.  👍

**Comment by dgutov** [comment] 2023-07-13 01:08
Thanks for testing, I've moved the feature to a dedicated PR, it needs to cook a little more.

In the meantime, on the subject of width of the ellipsis in CJK, we've got the following comment: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=64420#47

Does it match your experience? Do you perhaps have anything to add?

Bonus points for replying directly to Debbugs, if you're familiar with its usage.

**Comment by dgutov** [comment] 2023-08-11 23:56
Hi! Minor update.

While the new rendering method is on the back-burner (I think I'll merge it right after the release; it'll need a fair amount of testing), the master branch in Emacs now has the option `cjk-ambiguous-chars-are-wide`.

```el
(setopt cjk-ambiguous-chars-are-wide nil)
```

should fix display of popups with `…` in them. But not with uneven-width characters like hieroglyphs in your other examples (not in GUI, at least; in terminal they might be working out okay already since they're fully double-width there).

**Comment by templateK** [comment] 2023-08-15 01:31
It's good to hear that the feature is implemented in the upstream. By the looks of the changes of the `cjk-ambiguous-chars-are-wide` in the emacs code, I hardly think there will be any problem. 

All wide CJK characters are rendered as exactly two columns wide character in terminal in my system and AFAIK, it is also true for the most terminals. So, I'm sure there will be no alignment problem specific to CJK hieroglyphs.

Thank you for the awesome package and the effort to making it even better.

**Comment by dgutov** [comment] 2023-11-06 12:12
Now merged.

**Closed by dgutov** 2023-11-06 12:12 UTC
