### ISSUE TITLE
How to invalidate the candicates cache of the backend when completion prefix changed?

### ISSUE THREAD

**Issue by netjune** [company-mode/company-mode#955] opened 2020-02-21 15:34 UTC
see this bug: https://github.com/tigersoldier/company-lsp/issues/136

When completion prefix changes but the point doesn't, candicates should be refreshed but it wasn't.

**Comment by netjune** [comment] 2020-02-22 05:23
Now I think it is bug of company-mode. It only compares the current point with the saved one to decide whether to refresh candicates. In this case, the point doesn't change, but the prefix has changed (to nil).

**Comment by dgutov** [comment] 2020-02-22 08:13
I'll look into it, thanks for the report.

In the meantime, you can add `yas-expand` to the end of `company-continue-commands` (make sure it starts with `not`).

**Comment by dgutov** [comment] 2020-02-22 18:51
@netjune Please `M-x toggle-debug-on-error`, then reproduce the problem and post the backtrace.

**Comment by netjune** [comment] 2020-02-23 02:51
> In the meantime, you can add `yas-expand` to the end of `company-continue-commands` (make sure it starts with `not`).

It works. Thanks.

**Comment by netjune** [comment] 2020-02-23 02:51
The backstrace:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  downcase(nil)
  (let* ((prefix (company-lsp--completion-prefix)) (prefix-str (downcase (if (consp prefix) (car prefix) prefix))) (prefix-pos 0) (prefix-len (length prefix-str)) (candidate-pos 0) (candidate-len (length candidate)) (candidate-str (downcase candidate)) chunks chunk-start) (while (and (< prefix-pos prefix-len) (< candidate-pos candidate-len)) (if (= (aref prefix-str prefix-pos) (aref candidate-str candidate-pos)) (progn (if (not chunk-start) (progn (setq chunk-start candidate-pos))) (setq prefix-pos (1+ prefix-pos)) (setq candidate-pos (1+ candidate-pos))) (if chunk-start (progn (setq chunks (cons (cons chunk-start candidate-pos) chunks)) (setq chunk-start nil))) (setq candidate-pos (1+ candidate-pos)))) (if chunk-start (progn (setq chunks (cons (cons chunk-start candidate-pos) chunks)))) (nreverse chunks))
  company-lsp--compute-match(#("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch")))
  (cond ((eql command 'interactive) (company-begin-backend #'company-lsp)) ((eql command 'prefix) (and (and (boundp 'lsp-mode) lsp-mode) (lsp--capability "completionProvider") (not (company-in-string-or-comment)) (or (company-lsp--completion-prefix) 'stop))) ((eql command 'candidates) (or (company-lsp--cache-item-candidates (company-lsp--cache-get arg)) (and company-lsp-async (cons :async #'(lambda (callback) (company-lsp--candidates-async arg callback)))) (company-lsp--candidates-sync arg))) ((eql command 'sorted) t) ((eql command 'no-cache) (not (eq company-lsp-cache-candidates t))) ((eql command 'annotation) (lsp--annotate arg)) ((eql command 'quickhelp-string) (company-lsp--documentation arg)) ((eql command 'doc-buffer) (company-doc-buffer (company-lsp--documentation arg))) ((eql command 'match) (company-lsp--compute-match arg)) ((eql command 'post-completion) (company-lsp--post-completion arg)))
  company-lsp(match #("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch")))
  apply(company-lsp (match #("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch"))))
  (if (functionp company-backend) (apply company-backend args) (apply #'company--multi-backend-adapter company-backend args))
  (condition-case err (if (functionp company-backend) (apply company-backend args) (apply #'company--multi-backend-adapter company-backend args)) ((debug user-error) (user-error "Company: backend %s user-error: %s" company-backend (error-message-string err))) ((debug error) (error "Company: backend %s error \"%s\" with args %s" company-backend (error-message-string err) args)))
  company-call-backend-raw(match #("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch")))
  apply(company-call-backend-raw (match #("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch"))))
  (let ((value (apply fun args))) (if (not (eq (car-safe value) :async)) value (let ((res 'trash) (start (time-to-seconds))) (funcall (cdr value) #'(lambda (result) (setq res result))) (while (eq res 'trash) (if (> (- (time-to-seconds) start) company-async-timeout) (error "Company: backend %s async timeout with args %s" backend args) (sleep-for company-async-wait))) res)))
  company--force-sync(company-call-backend-raw (match #("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch"))) company-lsp)
  company-call-backend(match #("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch")))
  (or (company-call-backend 'match value) (if company-common (string-width company-common) 0))
  (let* ((margin (length left)) (common (or (company-call-backend 'match value) (if company-common (string-width company-common) 0))) (_ (setq value (company--pre-render value) annotation (and annotation (company--pre-render annotation t)))) (ann-ralign company-tooltip-align-annotations) (ann-truncate (< width (+ (length value) (length annotation) (if ann-ralign 1 0)))) (ann-start (+ margin (if ann-ralign (if ann-truncate (1+ (length value)) (- width (length annotation))) (length value)))) (ann-end (min (+ ann-start (length annotation)) (+ margin width))) (line (concat left (if (or ann-truncate (not ann-ralign)) (company-safe-substring (concat value (if ... ...) annotation) 0 width) (concat (company-safe-substring value 0 (- width ...)) annotation)) right))) (setq width (+ width margin (length right))) (font-lock-append-text-property 0 width 'mouse-face 'company-tooltip-mouse line) (if (< ann-start ann-end) (progn (font-lock-append-text-property ann-start ann-end 'face (if selected 'company-tooltip-annotation-selection 'company-tooltip-annotation) line))) (let* ((width (- width (length right))) (--cl-var-- (if (integerp common) (list (cons 0 common)) common)) (comp-end nil) (comp-beg nil) (inline-beg nil) (inline-end nil) (--cl-var-- t)) (while (consp --cl-var--) (setq comp-end (car --cl-var--) comp-beg (car-safe (prog1 comp-end (setq comp-end (cdr comp-end))))) (setq inline-beg (if --cl-var-- (+ margin comp-beg) (+ margin comp-beg))) (setq inline-end (if --cl-var-- (min (+ margin comp-end) width) (min (+ margin comp-end) width))) (if (< inline-beg width) (progn (font-lock-prepend-text-property inline-beg inline-end 'face (if selected 'company-tooltip-common-selection 'company-tooltip-common) line))) (setq --cl-var-- (cdr --cl-var--)) (setq --cl-var-- nil)) nil) (if (let ((re (funcall company-search-regexp-function company-search-string))) (and (not (string= re "")) (string-match re value (length company-prefix)))) (progn (let ((--dolist-tail-- (company--search-chunks))) (while --dolist-tail-- (let ((x18 ...)) (let* (... ...) (let ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--))))))) (if selected (progn (font-lock-append-text-property 0 width 'face 'company-tooltip-selection line))) (font-lock-append-text-property 0 width 'face 'company-tooltip line) line)
  company-fill-propertize(#("cha" 0 3 (lsp-completion-item #<hash-table equal 9/9 0x1ff3778e8bb5> lsp-completion-prefix "ch")) " \"golang.org/x/tools/go/callgraph/cha\" (Module)" 64 t " " " 1 ")
  (concat (company-fill-propertize str annotation width (equal i selection) left right) (if scrollbar-bounds (progn (company--scrollbar i scrollbar-bounds))))
  (cons (concat (company-fill-propertize str annotation width (equal i selection) left right) (if scrollbar-bounds (progn (company--scrollbar i scrollbar-bounds)))) new)
  (setq new (cons (concat (company-fill-propertize str annotation width (equal i selection) left right) (if scrollbar-bounds (progn (company--scrollbar i scrollbar-bounds)))) new))
  (let* ((item (car-safe (prog1 items (setq items (cdr items))))) (str (car item)) (annotation (cdr item)) (margin (company-space-string company-tooltip-margin)) (left margin) (right margin) (width width)) (if (< numbered 10) (progn (setq width (- width 2)) (setq numbered (1+ numbered)) (if (eq company-show-numbers 'left) (setq left (concat (funcall company-show-numbers-function numbered) margin)) (setq right (concat (funcall company-show-numbers-function numbered) margin))))) (setq new (cons (concat (company-fill-propertize str annotation width (equal i selection) left right) (if scrollbar-bounds (progn (company--scrollbar i scrollbar-bounds)))) new)))
  (let ((i --dotimes-counter--)) (let* ((item (car-safe (prog1 items (setq items (cdr items))))) (str (car item)) (annotation (cdr item)) (margin (company-space-string company-tooltip-margin)) (left margin) (right margin) (width width)) (if (< numbered 10) (progn (setq width (- width 2)) (setq numbered (1+ numbered)) (if (eq company-show-numbers 'left) (setq left (concat (funcall company-show-numbers-function numbered) margin)) (setq right (concat (funcall company-show-numbers-function numbered) margin))))) (setq new (cons (concat (company-fill-propertize str annotation width (equal i selection) left right) (if scrollbar-bounds (progn (company--scrollbar i scrollbar-bounds)))) new))))
  (while (< --dotimes-counter-- --dotimes-limit--) (let ((i --dotimes-counter--)) (let* ((item (car-safe (prog1 items (setq items ...)))) (str (car item)) (annotation (cdr item)) (margin (company-space-string company-tooltip-margin)) (left margin) (right margin) (width width)) (if (< numbered 10) (progn (setq width (- width 2)) (setq numbered (1+ numbered)) (if (eq company-show-numbers 'left) (setq left (concat ... margin)) (setq right (concat ... margin))))) (setq new (cons (concat (company-fill-propertize str annotation width (equal i selection) left right) (if scrollbar-bounds (progn ...))) new)))) (setq --dotimes-counter-- (1+ --dotimes-counter--)))
  (let ((--dotimes-limit-- len) (--dotimes-counter-- 0)) (while (< --dotimes-counter-- --dotimes-limit--) (let ((i --dotimes-counter--)) (let* ((item (car-safe (prog1 items ...))) (str (car item)) (annotation (cdr item)) (margin (company-space-string company-tooltip-margin)) (left margin) (right margin) (width width)) (if (< numbered 10) (progn (setq width (- width 2)) (setq numbered (1+ numbered)) (if (eq company-show-numbers ...) (setq left ...) (setq right ...)))) (setq new (cons (concat (company-fill-propertize str annotation width ... left right) (if scrollbar-bounds ...)) new)))) (setq --dotimes-counter-- (1+ --dotimes-counter--))))
  (let ((items (nreverse items)) (numbered (if company-show-numbers 0 99999)) new) (if previous (progn (setq new (cons (company--scrollpos-line previous width) new)))) (let ((--dotimes-limit-- len) (--dotimes-counter-- 0)) (while (< --dotimes-counter-- --dotimes-limit--) (let ((i --dotimes-counter--)) (let* ((item (car-safe ...)) (str (car item)) (annotation (cdr item)) (margin (company-space-string company-tooltip-margin)) (left margin) (right margin) (width width)) (if (< numbered 10) (progn (setq width ...) (setq numbered ...) (if ... ... ...))) (setq new (cons (concat ... ...) new)))) (setq --dotimes-counter-- (1+ --dotimes-counter--)))) (if remainder (progn (setq new (cons (company--scrollpos-line remainder width) new)))) (nreverse new))
  (let ((len company-candidates-length) (window-width (company--window-width)) lines width lines-copy items previous remainder scrollbar-bounds) (if (< len (+ company-tooltip-offset limit)) (progn (setq company-tooltip-offset 0))) (if (eq company-tooltip-offset-display 'lines) (setq limit (company-tooltip--lines-update-offset selection len limit)) (company-tooltip--simple-update-offset selection len limit)) (cond ((eq company-tooltip-offset-display 'scrollbar) (setq scrollbar-bounds (company--scrollbar-bounds company-tooltip-offset limit len))) ((eq company-tooltip-offset-display 'lines) (if (> company-tooltip-offset 0) (progn (setq previous (format "...(%d)" company-tooltip-offset)))) (setq remainder (- len limit company-tooltip-offset) remainder (if (> remainder 0) (progn (setq remainder (format "...(%d)" remainder))))))) (setq selection (- selection company-tooltip-offset)) (setq width (max (length previous) (length remainder)) lines (nthcdr company-tooltip-offset company-candidates) len (min limit len) lines-copy lines) (setq window-width (- window-width (* 2 company-tooltip-margin))) (if scrollbar-bounds (progn (setq window-width (1- window-width)))) (let ((--dotimes-limit-- len) (--dotimes-counter-- 0)) (while (< --dotimes-counter-- --dotimes-limit--) (let ((_ --dotimes-counter--)) (let* ((value (car-safe ...)) (annotation (company-call-backend ... value))) (setq value (company--clean-string (company-reformat value))) (if annotation (progn (setq annotation ...) (if company-tooltip-align-annotations ...))) (setq items (cons (cons value annotation) items)) (setq width (max (+ ... ...) width)))) (setq --dotimes-counter-- (1+ --dotimes-counter--)))) (setq width (min window-width company-tooltip-maximum-width (max company-tooltip-minimum-width (if company-show-numbers (+ 2 width) width)))) (let ((items (nreverse items)) (numbered (if company-show-numbers 0 99999)) new) (if previous (progn (setq new (cons (company--scrollpos-line previous width) new)))) (let ((--dotimes-limit-- len) (--dotimes-counter-- 0)) (while (< --dotimes-counter-- --dotimes-limit--) (let ((i --dotimes-counter--)) (let* ((item ...) (str ...) (annotation ...) (margin ...) (left margin) (right margin) (width width)) (if (< numbered 10) (progn ... ... ...)) (setq new (cons ... new)))) (setq --dotimes-counter-- (1+ --dotimes-counter--)))) (if remainder (progn (setq new (cons (company--scrollpos-line remainder width) new)))) (nreverse new)))
  company--create-lines(0 10)
  (let ((lines (company--create-lines selection (abs height)))) (overlay-put ov 'company-display (apply 'company--replacement-string lines args)) (overlay-put ov 'company-width (string-width (car lines))))
  (let (nl beg end ov args) (save-excursion (setq nl (< (move-to-window-line row) row) beg (point) end (save-excursion (move-to-window-line (+ row (abs height))) (point)) ov (make-overlay beg end nil t) args (list (mapcar 'company-plainify (company-buffer-lines beg end)) column nl above))) (setq company-pseudo-tooltip-overlay ov) (overlay-put ov 'company-replacement-args args) (let ((lines (company--create-lines selection (abs height)))) (overlay-put ov 'company-display (apply 'company--replacement-string lines args)) (overlay-put ov 'company-width (string-width (car lines)))) (overlay-put ov 'company-column column) (overlay-put ov 'company-height height))
  (let* ((height (company--pseudo-tooltip-height)) above) (if (< height 0) (progn (setq row (+ row height -1) above t))) (let (nl beg end ov args) (save-excursion (setq nl (< (move-to-window-line row) row) beg (point) end (save-excursion (move-to-window-line (+ row (abs height))) (point)) ov (make-overlay beg end nil t) args (list (mapcar 'company-plainify (company-buffer-lines beg end)) column nl above))) (setq company-pseudo-tooltip-overlay ov) (overlay-put ov 'company-replacement-args args) (let ((lines (company--create-lines selection (abs height)))) (overlay-put ov 'company-display (apply 'company--replacement-string lines args)) (overlay-put ov 'company-width (string-width (car lines)))) (overlay-put ov 'company-column column) (overlay-put ov 'company-height height)))
  company-pseudo-tooltip-show(26 4 0)
  (let* ((col-row (company--col-row pos)) (col (- (car col-row) column-offset))) (if (< col 0) (progn (setq col 0))) (company-pseudo-tooltip-show (1+ (cdr col-row)) col company-selection))
  company-pseudo-tooltip-show-at-point(5152 2)
  (if (if (overlayp company-pseudo-tooltip-overlay) (progn (let* ((ov company-pseudo-tooltip-overlay) (old-height (overlay-get ov 'company-height)) (new-height (company--pseudo-tooltip-height))) (and (>= (* old-height new-height) 0) (>= (abs old-height) (abs new-height)) (equal (company-pseudo-tooltip-guard) (overlay-get ov 'company-guard)))))) nil (company-pseudo-tooltip-show-at-point (point) (length company-prefix)) (overlay-put company-pseudo-tooltip-overlay 'company-guard (company-pseudo-tooltip-guard)))
  (cond ((eql command 'pre-command) (company-pseudo-tooltip-hide-temporarily)) ((eql command 'post-command) (if (if (overlayp company-pseudo-tooltip-overlay) (progn (let* ((ov company-pseudo-tooltip-overlay) (old-height ...) (new-height ...)) (and (>= ... 0) (>= ... ...) (equal ... ...))))) nil (company-pseudo-tooltip-show-at-point (point) (length company-prefix)) (overlay-put company-pseudo-tooltip-overlay 'company-guard (company-pseudo-tooltip-guard))) (company-pseudo-tooltip-unhide)) ((eql command 'hide) (company-pseudo-tooltip-hide) (setq company-tooltip-offset 0)) ((eql command 'update) (if (overlayp company-pseudo-tooltip-overlay) (progn (company-pseudo-tooltip-edit company-selection)))))
  company-pseudo-tooltip-frontend(post-command)
  (if (and (eq command 'post-command) (company--show-inline-p)) nil (company-pseudo-tooltip-frontend command))
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  funcall(company-pseudo-tooltip-unless-just-one-frontend post-command)
  (condition-case err (funcall frontend command) ((debug error) (error "Company: frontend %s error \"%s\" on command %s" frontend (error-message-string err) command)))
  (let ((frontend (car --dolist-tail--))) (condition-case err (funcall frontend command) ((debug error) (error "Company: frontend %s error \"%s\" on command %s" frontend (error-message-string err) command))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((frontend (car --dolist-tail--))) (condition-case err (funcall frontend command) ((debug error) (error "Company: frontend %s error \"%s\" on command %s" frontend (error-message-string err) command))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- company-frontends)) (while --dolist-tail-- (let ((frontend (car --dolist-tail--))) (condition-case err (funcall frontend command) ((debug error) (error "Company: frontend %s error \"%s\" on command %s" frontend (error-message-string err) command))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  company-call-frontends(post-command)
  (if company-candidates (company-call-frontends 'post-command) (let ((delay (company--idle-delay))) (and (numberp delay) (not defining-kbd-macro) (company--should-begin) (setq company-timer (run-with-timer delay nil 'company-idle-begin (current-buffer) (selected-window) (buffer-chars-modified-tick) (point))))))
  (progn (if (equal (point) company-point) nil (let (company-idle-delay) (company--perform))) (if company-candidates (company-call-frontends 'post-command) (let ((delay (company--idle-delay))) (and (numberp delay) (not defining-kbd-macro) (company--should-begin) (setq company-timer (run-with-timer delay nil 'company-idle-begin (current-buffer) (selected-window) (buffer-chars-modified-tick) (point)))))))
  (condition-case err (progn (if (equal (point) company-point) nil (let (company-idle-delay) (company--perform))) (if company-candidates (company-call-frontends 'post-command) (let ((delay (company--idle-delay))) (and (numberp delay) (not defining-kbd-macro) (company--should-begin) (setq company-timer (run-with-timer delay nil 'company-idle-begin (current-buffer) (selected-window) (buffer-chars-modified-tick) (point))))))) ((debug error) (message "Company: An error occurred in post-command") (message "%s" (error-message-string err)) (company-cancel)))
  (if (company-keep this-command) nil (condition-case err (progn (if (equal (point) company-point) nil (let (company-idle-delay) (company--perform))) (if company-candidates (company-call-frontends 'post-command) (let ((delay (company--idle-delay))) (and (numberp delay) (not defining-kbd-macro) (company--should-begin) (setq company-timer (run-with-timer delay nil ... ... ... ... ...)))))) ((debug error) (message "Company: An error occurred in post-command") (message "%s" (error-message-string err)) (company-cancel))))
  company-post-command()
```

**Comment by dgutov** [comment] 2020-02-23 09:19
This looks more like `company-lsp`'s problem, actually. /Cc @yyoncho

**Comment by yyoncho** [comment] 2020-02-23 11:08
@netjune we are moving our focus on company-capf implementation so atm company-lsp is unmaitained.

**Comment by netjune** [comment] 2020-02-23 12:38
> @netjune we are moving our focus on company-capf implementation so atm company-lsp is unmaitained.

OK. Thanks.

**Comment by netjune** [comment] 2020-02-23 12:45
> This looks more like `company-lsp`'s problem, actually. /Cc @yyoncho

I see that at that time, the backend(company-lsp) is called with arg match and candicates. What should it return to tell company-mode to refresh the candicates? I let it return nil, but the completion menu still popups.

**Comment by dgutov** [comment] 2020-02-23 22:51
That's not how it works. If it calls `match`, earlier it received a list of candidates. And at *that* time it should have received a different list (maybe nil). Or, even before that, should have received `nil` as the response to the `prefix` command.

**Comment by netjune** [comment] 2020-02-24 02:21
I remember that `prefix` command was not called after yas-expand. The cache is enabled in company-lsp. And the point is the same as before yas-expand. So company-mode seems not call prefix after yas-expand and it uses the cached candicates.

**Comment by dgutov** [comment] 2020-02-24 08:52
It must be called. `company--continue` calls it.

**Comment by netjune** [comment] 2020-02-25 02:43
No. It doesn't.

I added this line to the start of `company-lsp`:
```
  (message "------ cmd: %s" command)
```

The following is the output message:
```
------ cmd: prefix
------ cmd: require-match
------ cmd: candidates
------ cmd: sorted
------ cmd: duplicates
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: prefix [2 times]
------ cmd: require-match
------ cmd: candidates
------ cmd: sorted
------ cmd: duplicates
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
------ cmd: match
------ cmd: pre-render [2 times]
Loading snippets in /Users/jun/.snippets/go-mode ...
Loading snippets in /Users/jun/.lisp/snippets/go-mode ...
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: annotation
------ cmd: ignore-case
------ cmd: match
```
There are two lines in them: 
```
Loading snippets in /Users/jun/.snippets/go-mode ...
Loading snippets in /Users/jun/.lisp/snippets/go-mode ...
```
`yas-expand` run here.

We can see that after `yas-expand`, there are no `prefix` called.

**Comment by netjune** [comment] 2020-02-25 03:02
I think in `company-post-command`:
```
(defun company-post-command ()
  (when (and company-candidates
             (null this-command))
    ;; Happens when the user presses `C-g' while inside
    ;; `flyspell-post-command-hook', for example.
    ;; Or any other `post-command-hook' function that can call `sit-for',
    ;; or any quittable timer function.
    (company-abort)
    (setq this-command 'company-abort))
  (unless (company-keep this-command)
    (condition-case-unless-debug err
        (progn
          (unless (equal (point) company-point)
            (let (company-idle-delay) ; Against misbehavior while debugging.
              (company--perform)))
          (if company-candidates
              (company-call-frontends 'post-command)
            (let ((delay (company--idle-delay)))
             (and (numberp delay)
                  (not defining-kbd-macro)
                  (company--should-begin)
                  (setq company-timer
                        (run-with-timer delay nil
                                        'company-idle-begin
                                        (current-buffer) (selected-window)
                                        (buffer-chars-modified-tick) (point)))))))
      (error (message "Company: An error occurred in post-command")
             (message "%s" (error-message-string err))
             (company-cancel))))
  (company-install-map))
```
Most conditions are not sitisfied in this case. So it only calls
```
              (company-call-frontends 'post-command)
```

**Comment by dgutov** [comment] 2020-02-27 07:47
Hmm, you seem to be right. I'll see what can be done here.

**Comment by dgutov** [comment] 2020-03-01 22:44
@netjune Does simply removing the check help?

```diff
diff --git a/company.el b/company.el
index 34f90de..8d451cf 100644
--- a/company.el
+++ b/company.el
@@ -1716,9 +1716,8 @@ prefix match (same case) will be prioritized."
   (unless (company-keep this-command)
     (condition-case-unless-debug err
         (progn
-          (unless (equal (point) company-point)
-            (let (company-idle-delay) ; Against misbehavior while debugging.
-              (company--perform)))
+          (let (company-idle-delay) ; Against misbehavior while debugging.
+            (company--perform))
           (if company-candidates
               (company-call-frontends 'post-command)
             (let ((delay (company--idle-delay)))
```

**Comment by dgutov** [comment] 2020-03-01 22:48
Although that results in more calls to `company--perform`.

**Comment by dgutov** [comment] 2020-03-01 22:54
I suppose we could also add a var that would track the last value of `(buffer-chars-modified-tick)`, and compare it as well.

The situation seems rare enough (snippet the same length as its key), and the problem is triggered by the backend re-calculating the prefix instead of using the value known to company (either from backend action argument, or from the global var `company-prefix`).

**Comment by netjune** [comment] 2020-03-02 07:27
> I suppose we could also add a var that would track the last value of `(buffer-chars-modified-tick)`, and compare it as well.

Yes.

> The situation seems rare enough (snippet the same length as its key), 

In fact, the snippet expands `ch` to `->|channel_name`, while `|` is the cursor. The point doesn't change.

>and the problem is triggered by the backend re-calculating the prefix instead of using the value known to company (either from backend action argument, or from the global var `company-prefix`).

How to cancel completion in backend? I let company-lsp return nil for `match`. But the completion menu still popups.

**Comment by dgutov** [comment] 2020-05-06 01:35
Care to try this patch?

```diff
diff --git a/company.el b/company.el
index 428fc32..954b9ca 100644
--- a/company.el
+++ b/company.el
@@ -1520,10 +1520,14 @@ prefix match (same case) will be prioritized."
   (and (> (point) company-point)
        (> (point-max) company--point-max)
        (not (eq this-command 'backward-delete-char-untabify))
-       (equal (buffer-substring (- company-point (length company-prefix))
-                                company-point)
+       (equal (company--prefix-buffer-substring company-point)
               company-prefix)))
 
+(defun company--prefix-buffer-substring (pos)
+  (buffer-substring-no-properties
+   (- pos (length company-prefix))
+   pos))
+
 (defun company--continue-failed (new-prefix)
   (cond
    ((and (or (not (company-require-match-p))
@@ -1718,7 +1722,9 @@ prefix match (same case) will be prioritized."
   (unless (company-keep this-command)
     (condition-case-unless-debug err
         (progn
-          (unless (equal (point) company-point)
+          (unless (and (equal (point) company-point)
+                       (equal company-prefix
+                              (company--prefix-buffer-substring (point))))
             (let (company-idle-delay) ; Against misbehavior while debugging.
               (company--perform)))
           (if company-candidates
```

**Comment by netjune** [comment] 2020-05-07 01:44
Now I think there is no need to fix it because there may be a command which modifies the buffer content a lot and just keep the point and completion prefix not changed, in which case the completion context may changed and the cached completion candicates should be invalidated.

I think your first suggestion is good enough as the solution:
>In the meantime, you can add yas-expand to the end of company-continue-commands (make sure it starts with not).

What do you think?

**Comment by dgutov** [comment] 2020-05-07 02:22
Fair enough, thanks. Let's close this for now, and if it ever comes up again, choose a more robust fix.

**Closed by dgutov** 2020-05-07 02:22 UTC
