### ISSUE TITLE
Can the common part to be selected by company-complete-common get a face?

### ISSUE THREAD

**Issue by sooheon** [company-mode/company-mode#519] opened 2016-05-23 12:44 UTC
What I mean is, when you have say TAB bound to complete-common-or-cycle, you never know if pressing it will cycle or complete common without trying it. For example, in the pic below pressing tab will complete all the way to `deactivate-`, but there is nothing to indicate that except trial and error (or looking at candidates and parsing the common prefix).

<img width="683" alt="screen shot 2016-05-23 at 8 29 21 pm" src="https://cloud.githubusercontent.com/assets/302945/15471098/2f152572-212f-11e6-83d7-092b8e5c3ab1.png">

**Comment by dgutov** [comment] 2016-05-30 23:12
I'll look into it.

**Comment by yugaego** [comment] 2021-09-17 02:39
Hi @dgutov , I've tested with 

```
(with-eval-after-load 'company
  (define-key company-active-map (kbd "<tab>") #'company-complete-common-or-cycle))

  (defvar deactivate-cursor-after-undo 1)
  (defvar deactivate-input-method 1)
  (defvar deactivate-mark 1)
  (defvar deactivate-mode-local-bindings 1)
```

And it works fine for me:

<img width="440" alt="dea" src="https://user-images.githubusercontent.com/296460/133715253-ad0bfe7e-f4db-4c5a-9dcb-8ff2ab9d4516.png">

<img width="446" alt="deac" src="https://user-images.githubusercontent.com/296460/133715263-54068de7-0144-4343-a5ee-9f28aaca8498.png">

Can you reproduce the issue?

**Comment by dgutov** [comment] 2021-09-17 18:09
Hi @yugaego!

I still can. What backend are you currently using on the screenshots and which Emacs? With `company-capf` and Emacs 27 or 28, I'm only seeing the behavior like in the report.

This turns out to be a little trickier than I thought.

Popup rendering happens in `company-fill-propertize`. When I traced its execution with edebug, it turned out `(company-call-backend 'match value)` returns list of intervals `((0 . 4))`. That logic lives in `company-capf`.

So our original `company-common` logic (which includes the part of the string that can still be completed) conflicts with the logic from capf which simply returns the currently matched parts of the string.

So... there might be a better choice, but to keep the "common" highlighting logic working, we can do this:

```diff
diff --git a/company.el b/company.el
index 9704a73..d055a46 100644
--- a/company.el
+++ b/company.el
@@ -2972,12 +2972,20 @@ If SHOW-VERSION is non-nil, show the version in the echo area."
       (pop copy))
     (apply 'concat pieces)))
 
+(defun company--common-or-matches (value)
+  (let ((matches (company-call-backend 'match value)))
+    (when (and matches
+               (= 1 (length matches))
+               (= 0 (caar matches))
+               (> (string-width company-common) (cdar matches)))
+      (setq matches nil))
+    (or matches
+        (and company-common (string-width company-common))
+        0)))
+
 (defun company-fill-propertize (value annotation width selected left right)
   (let* ((margin (length left))
-         (common (or (company-call-backend 'match value)
-                     (if company-common
-                         (string-width company-common)
-                       0)))
+         (common (company--common-or-matches value))
          (_ (setq value (company-reformat (company--pre-render value))
                   annotation (and annotation (company--pre-render annotation t))))
          (ann-ralign company-tooltip-align-annotations)
```

The alternative would be to split it into two faces, I guess. One for matching chars, another for "common" chars which will be inserted by "complete common".

But I'm not sure how to make a smooth transition, or whether we should. Perhaps simply committing the patch above and waiting for reports can answer the latter question.

**Comment by yugaego** [comment] 2021-09-18 15:56
Eventually, I reproduced the issue 😉 

```elisp
(setq company-frontends '(company-pseudo-tooltip-frontend
                       company-preview-frontend
                       company-echo-frontend))
```

<img width="811" alt="reproduced" src="https://user-images.githubusercontent.com/296460/133894256-d64fa9c3-ada1-4fde-b135-f52a15d1b3df.png">

And the FIXME note in `company-echo-format`, saying:
```
          ;; FIXME: Add support for the `match' backend action, and thus,
          ;; non-prefix matches.
```
explains (together with the rest of the source) why those frontends show expected results.

Well, for me the next step is to go and figure what the term "matches" *exactly* means and does visually, so I'll get back to you after that.
(I'm also going to install the patch you sent to see if it causes any troubles on my side).

**Comment by dgutov** [comment] 2021-09-19 11:06
Yeah, the echo frontends might need to be updated. But your previous screenshot showed a popup frontend, so I'm not sure how it behaved the same.

> Well, for me the next step is to go and figure what the term "matches" exactly means and does visually, so I'll get back to you after that.

:thumbsup:

There is a documented description of `match` in `company-backends`, which basically conflicts with the historical expectations of the highlighting of the common part, described in first message here.

**Comment by yugaego** [comment] 2021-09-19 13:19
> your previous screenshot showed a popup frontend, so I'm not sure how it behaved the same.

You should see that result with
 ```
(setq company-frontends '(company-pseudo-tooltip-unless-just-one-frontend-with-delay))
```

**Comment by yugaego** [comment] 2021-09-19 13:41
Sorry, I cannot provide a reliable recipe for this incorrectly correct behavior.
Now, sarcastically in opposite to the initial attempts to reproduce, I rarely see popup with the correct colors.

The main idea behind is:
- Use setup described in #1214  (including `C-c c` to raise tooltip and see correct colors in both tooltip and preview).
- Remove `company-preview-frontend` at some stage.
- Probably set `company-tooltip-idle-delay` to 1 or 0 at some stage too.

**Comment by yugaego** [comment] 2021-09-20 16:09
Hi Dmitry,

I'm still lacking a bit the domain knowledge, but might be some of the ideas would add wood to this topic fire.

**Part 1**

> The alternative would be to split it into two faces, I guess. One for matching chars, another for "common" chars which will be inserted by "complete common".

As I understand it, both terms mean the same thing: **Matches**, with 
- **common** standing for "prefix matches".
- and **matches** standing for "non-prefix (flex) matches".

Hence, the same face, visually, would be a preferred approach, IMO.

**Part 2**

Since "*non-prefix matches*" is a later addition to `Company`, are there any plans (or feasible at all) to switch to
always handling **Matches** as a superset of both "*non-prefix matches*" and "*prefix matches*", probably in all the supported backends?

This way,

> So our original company-common logic (which includes the part of the string that can still be completed) conflicts with the logic from capf which simply returns the currently matched parts of the string.

would have to be replaced by the **Matches** logic, that would have to provide possibility to complete a *match* at a point.

> But I'm not sure how to make a smooth transition, or whether we should. Perhaps simply committing the patch above and waiting for reports can answer the latter question.

Yes, probably (if that wouldn't make future possible changes to "**matches**"/"**common**" even more complicated.)
I'm living with this patch so far fine, but I'm not a strong user of "*non-prefix matches*".

**Part 3**

<img width="356" alt="matches" src="https://user-images.githubusercontent.com/296460/134032878-e7c4df50-a1a8-4679-a13c-3e3a6b556056.png">

As a side note, I noticed that `company--search-chunks` are highlighted in the `preview-frontend`, but "**matches**" are not.
So, seems, it would be desirable to have "**matches**" support in `preview-frontend` too?

**Comment by dgutov** [comment] 2021-09-20 23:53
Hi Yuzhana!

> common standing for "prefix matches"

The "common part" highlighting indeed originated when prefix matching was the only available matching mechanism. But it didn't show only the "matched" part. It rather showed the common part of all available completions (the longest common prefix), no matter what the input was (which had to be a prefix of the "common part").

Rather than annotate the matching part (which was obvious at the time and would look like a rectangle repeating the same chars -- the input -- 10 times or so), it annotated the part which would be completed if the user presses TAB. Just like the first message here requests.

> are there any plans (or feasible at all) to switch to
always handling Matches as a superset of both "non-prefix matches" and "prefix matches", probably in all the supported backends?

It will be good to handle them as uniformly as possible. Up until now, I guess I have added support to the commonly used backends and mostly ignored the rest (like the echo backend), alas.

> So, seems, it would be desirable to have "matches" support in preview-frontend too?

Maybe? Alternatively, consider that `preview-frontend` is not a good choice for non-prefix matches. That's why `company-preview-if-just-one-frontend` actually uses a helper `company--show-inline-p` that also disables it (delegating to the popup frontend) if matching is non-prefix.

Because it's really non-obvious to me how to render the preview frontend when the matching part is not at the beginning of the string. Right now it's clearly broken, since it simply cuts off the first len(prefix) characters from the completion before displaying it.

**Comment by yugaego** [comment] 2021-09-21 07:57
> It rather showed the common part of all available completions (the longest common prefix), no matter what the input was (which had to be a prefix of the "common part").

I appreciate the clarification. Indeed, I missed this quite obvious detail, and it would make faces separation a reasoned action. 

> It will be good to handle them as uniformly as possible.

👍🏻

**Closed** 2021-09-26 21:34 UTC
Labels: wishlist

**Comment by dgutov** [comment] 2021-09-26 23:55
> Because it's really non-obvious to me how to render the preview frontend when the matching part is not at the beginning of the string. Right now it's clearly broken, since it simply cuts off the first len(prefix) characters from the completion before displaying it.

Hopefully fixed now.

`match` support added as well.

**Comment by yugaego** [comment] 2021-09-28 11:02
👍🏻  Kudos for adding `match` support for preview frontend.
