### ISSUE TITLE
Error completing namespace alias prefix in Clojure

### ISSUE THREAD

**Issue by cch1** [company-mode/company-mode#1428] opened 2023-11-14 17:10 UTC
Since update to company 0.10.2 this morning, I am seeing the following error:

`Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Text is read-only" on command post-command`

This error appears when starting a function invocation in Clojure.

#### Output of the command `M-x company-diag`
```
Emacs 29.1 (aarch64-apple-darwin21.6.0) of 2023-08-16 on armbob.lan
Company 0.10.2

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (cider-complete-at-point t)
Major mode: clojure-mode
Prefix: "codec/"
Completions:
  #("codec/assoc-conj" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/url-decode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/url-encode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/form-decode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/form-encode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/form-encode*" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/base64-decode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/base64-encode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/FormEncodeable" 0 1 (face (completions-common-part) ns "ring.util.codec" type "var") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference))) " <v>"
  #("codec/percent-decode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/percent-encode" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/form-decode-str" 0 1 (face (completions-common-part) ns "ring.util.codec" type "function") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference)))
  #("codec/fix-string-replace-bug" 0 1 (face (completions-common-part) ns "ring.util.codec" type "macro") 1 6 (face (completions-common-part)) 6 7 (face (completions-first-difference))) " <m>"
```
- If the value is `company-capf`, then one more clue is on the line starting with `Value of c-a-p-f:`
  -  The issue could have been caused by a function listed there.
  -  Use `M-x find-function RET <function-name> RET` to identify which package it belongs to.

#### Describe the issue
Since update to company 0.10.2 this morning, I am seeing these errors when entering a Clojure function:

```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Text is read-only" on command post-command
```

#### Steps to reproduce
Reproducing the error is not (yet) trivial -when first starting emacs, the error does not manifest.  But once past some unknown threshold, the error appears every time when typing a function prefix (with or without a namespace prefix).

#### Expected behavior
I expect to be able to auto-complete functions without drama.

#### The error backtrace
```
Debugger entered--Lisp error: (error "Company: frontend company-pseudo-tooltip-unless-just-one-frontend error \"Text is read-only\" on command post-command")
  signal(error ("Company: frontend company-pseudo-tooltip-unless-ju..."))
  error("Company: frontend %s error \"%s\" on command %s" company-pseudo-tooltip-unless-just-one-frontend "Text is read-only" post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer url.clj> #<window 3 on url.clj> 1609 784)
  apply(company-idle-begin (#<buffer url.clj> #<window 3 on url.clj> 1609 784))
  timer-event-handler([t 25939 41445 816373 nil company-idle-begin (#<buffer url.clj> #<window 3 on url.clj> 1609 784) nil 0 nil])
```
#### Additional context
The threshold past which the error appears constantly is not starting ClojureMode.  Nor is it starting Cider.  Nor is it "jacking in" with Cider to start a REPL.

The error appears in text buffers as well as CIDER REPL buffers.

**Comment by vemv** [comment] 2023-11-14 17:16
As some extra context, another user mentioned:

> I just encountered this and worked around it by pinning company (the package) to melpa-stable instead of the latest git.

CIDER-side, we haven't changed anything related to Company interaction.

**Comment by dgutov** [comment] 2023-11-15 01:38
@vemv It might as well be a bug here. I've merged some major rework lately.

@cch1 To get the backtrace, you have `M-x toggle-debug-on-error`, right?

In the same context/situation where you see the error, could you also explicitly invoke `M-x company-complete-common`? I'm hoping this will lead to a fuller backtrace being printed.

**Comment by dgutov** [comment] 2023-11-15 01:44
@cch1 And when we're talking about upgrading to 0.10.2, you have actually upgraded through MELPA, right (to the latest snapshot)? In the list of installed packages it would be shown as a timestamp version, `M-x company-diag` just doesn't know how to detect and print it yet.

**Comment by cch1** [comment] 2023-11-15 02:21
> @cch1 And when we're talking about upgrading to 0.10.2, you have actually upgraded through MELPA, right (to the latest snapshot)? In the list of installed packages it would be shown as a timestamp version, `M-x company-diag` just doesn't know how to detect and print it yet.

Yes.  In the list of installed packages it was a timestamp version.  Unpinning to test now, I see `20231110.52` and, unless something newer was released during the day, that was probably the version this morning when I was having the issue (before pinning to melpa-stable).

**Comment by cch1** [comment] 2023-11-15 02:22
> @cch1 To get the backtrace, you have `M-x toggle-debug-on-error`, right?
Correct -per your useful error reporting instructions!
> 
> In the same context/situation where you see the error, could you also explicitly invoke `M-x company-complete-common`? I'm hoping this will lead to a fuller backtrace being printed.

I'll try unpinning and, if I can provoke the error, I'll run that command.

**Comment by dgutov** [comment] 2023-11-15 18:31
And as a wild guess, here's a patch you could try when you reproduce the problem:

```diff
diff --git a/company.el b/company.el
index 89f68fd..0b75547 100644
--- a/company.el
+++ b/company.el
@@ -2968,6 +2968,7 @@ from the candidates list.")
         front back
         (orig-buf (window-buffer))
         (bis buffer-invisibility-spec)
+        (inhibit-read-only t)
         window-configuration-change-hook)
     (with-current-buffer (get-buffer-create " *company-sps*")
       (unwind-protect
```

To confirm it, you first need to see the error, then apply the patch, re-eval the function (with `C-M-x`) and check that the problem is gone.

**Comment by vemv** [comment] 2023-11-15 18:34
That would make sense since clojure repls have a read-only part (the prompt)

I'll try to repro myself (never had since I'm on Git) - no promises though ^^

**Comment by dgutov** [comment] 2023-11-15 18:50
> That would make sense since clojure repls have a read-only part (the prompt)

That might explain why the error could be Clojure-specific, but not why it (reportedly) takes a while to reproduce, or which part of the code became "mutating" to cause the error.

> I'll try to repro myself (never had since I'm on Git) - no promises though ^^

Thanks! And if the patch doesn't help, and the backtrace is still short, `M-: (load "company") RET` might be another thing to improve the latter.

**Comment by cch1** [comment] 2023-11-15 20:07
After unpinning the package this morning, the error still has not manifested itself.  I'm starting to question whether the unpinning actually had an effect -or if a more recent version of company has been installed than the one I got yesterday morning.

**Comment by cch1** [comment] 2023-11-15 21:43
Finally triggered the error mode -seemed to correlate with auto-completing a Java class method.

Here's the even-shorter backtrace from `company-complete-common`:
```
Debugger entered--Lisp error: (error "Company: frontend company-pseudo-tooltip-unless-ju...")
  signal(error ("Company: frontend company-pseudo-tooltip-unless-ju..."))
  error("Company: frontend %s error \"%s\" on command %s" company-pseudo-tooltip-unless-just-one-frontend "Text is read-only" post-command)
  company-call-frontends(post-command)
  company-post-command()
```

Then I went to apply the patch by opening the file `~/.emacs.d/elpa/company-20231110.52/company.el` and along the way noticed the error was happening even in elisp files.

But, the good news: after applying the patch, the problem went away.

**Comment by dgutov** [comment] 2023-11-15 22:52
I'm puzzled why the backtrace is this short -- perhaps indeed because the file is compiled, and evaluating `(load ...)` would help.

Anyway, the news is good indeed. Thanks for testing, I'll push that change.

**Closed** 2023-11-15 22:55 UTC
