### ISSUE TITLE
Completion inside word

### ISSUE THREAD

**Issue by jscheid** [company-mode/company-mode#1106] opened 2021-05-23 00:33 UTC
Perhaps it's just me but quite often I find myself wanting to replace a subword, for example:

`addFoo|Prop`  ▶️ `DEL` `DEL` `DEL` `Bar` ▶️ `addBar|Prop` (or using `backward-kill-word` with `subword-mode`.)

Let's say my completion candidates include `addBarProp`, `addBazProp`, and `addBaaa`. Then when I start doing

`addFoo|Prop`  ▶️ `DEL` `DEL` `DEL` `B`

... then with company-mode I will end up with a menu with those three candidates. Now selecting either of them will leave the buffer at:
`addBarProp|Prop`,
`addBazProp|Prop`, or
`addBaaa|Prop`,

... and at least the first two are not ideal.

Of course this is easily fixed with `kill-word`, either before typing `B` or after selecting the completion, but I was thinking it would be nice if company-mode could notice that what I'm really looking for is `addB*Prop`. It would then prioritize `addBarProp` and `addBazProp` as candidates (sort `addBaaa` behind them) and let me do:

`addFoo|Prop`  ▶️ `DEL` `DEL` `DEL` `B` `RET` ▶️ `addBarProp|` (or `addBar|Prop`, not sure which is better, I don't care too much)
... or ...
`addFoo|Prop`  ▶️ `DEL` `DEL` `DEL` `B` `<down>` `RET` ▶️ `addBazProp|`
... or ...
`addFoo|Prop`  ▶️ `DEL` `DEL` `DEL` `B` `<down>` `<down>` `RET` ▶️ `addBaaa|Prop`

I can see how in some situations this isn't the desired behavior but I believe most of the time it would be. What do you think?

Sorry if this was discussed before or is just a configuration issue.

**Comment by dgutov** [comment] 2021-05-23 00:37
Which backend are you using in these scenarios? `M-x company-diag` can help answer that question.

**Comment by jscheid** [comment] 2021-05-23 00:38
`company-capf` (with `lsp-mode`.) Am I barking up the wrong tree?

**Comment by dgutov** [comment] 2021-05-23 00:43
Yes and no. There is a feature in the works for Company for (hopefully) making this more streamlined, but as far as `lsp-mode` goes, they have merged a solution on their end for this recently: https://github.com/emacs-lsp/lsp-mode/pull/2711

So either `C-u RET` or `C-RET` should work for you.

**Comment by jscheid** [comment] 2021-05-23 00:57
Ah, interesting. I can't seem to get that to work yet with `lsp-mode 20210521.446` and `company 20210522.1921` but it's probably something at my end. Anyway, that sounds pretty close to what I'm looking for, thanks for the pointer!

Looking forward to your streamlined implementation, I see you've already been thinking of taking the suffix into consideration.

**Comment by jscheid** [comment] 2021-05-23 01:15
I think it's not working because `ts-ls` doesn't support `completion/insertReplaceSupport`.

**Comment by dgutov** [comment] 2023-10-12 01:27
Anyway, on the higher level, it's a duplicate of #340.

But I'm keeping this open for the link to a useful discussion (in lsp-mode), and to note that an `insert/replace` backend action (to override default behavior) mentioned in that issue might also be helpful to implement #792.

**Closed** 2024-07-13 03:04 UTC
