### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by tuhdo** [company-mode/company-mode#296] opened 2015-02-04 19:26 UTC
Someone implemented fuzzy matching with company: http://sixty-north.com/blog/a-more-full-featured-company-mode-backend, although rudimentary. I wonder if we can integrate with existing solution like flx? That would improve usability a lot.

**Comment by dgutov** [comment] 2015-02-04 19:29
No: they implemented a backend that performs fuzzy matching. It could use `flx`, or any other method, but doing fuzzy matching for all backends imposes different requirements on the framework (Company).

**Comment by tuhdo** [comment] 2015-02-05 05:13
So, it is possible to integrate `flx` for Emacs Lisp and dabbrev backends and gradually add more in the future? When I see [this article](http://endlessparentheses.com/new-on-elpa-speed-of-thought-lisp.html), I thought that what we need is a proper fuzzy completion engine rather than manually specify abbrevs.

**Comment by dgutov** [comment] 2015-02-05 06:20
> So, it is possible to integrate flx for Emacs Lisp

No, it's not. Or not not particularly easy, at least. On the other hand, `(add-to-list 'completion-styles 'initials t)` will get you almost the same benefits.

> and dabbrev

That's easier, but it would involve collecting *all* words from buffers and applyling `flx` to them. Which is necessarily slower than what we're doing now (we filter by prefix while searching). I'll let yourself measure, by how much.

Anyway, we can't use `flx` directly until it's in GNU ELPA.

**Comment by tuhdo** [comment] 2015-02-05 06:48
> (add-to-list 'completion-styles 'initials t)

I've just added it but when I tried `company-elisp` on string "wcb" or "atl" (add-to-list), it cannot complete.

**Comment by dgutov** [comment] 2015-02-05 06:55
You should try `company-capf` instead.

**Comment by tuhdo** [comment] 2015-02-05 06:59
Nice. But how can I type to start narrow to a single candidate? Currently, it only gives a list and prevent me from entering anything.

**Comment by dgutov** [comment] 2015-02-05 07:00
That might be impossible: initials means initials.

You can write your own completion style, however, but that's not a trivial task.

**Comment by tuhdo** [comment] 2015-02-05 07:02
Alright. This is good enough. I might combine it with `C-M-s` to narrow further.

**Comment by dgutov** [comment] 2015-02-05 09:10
What exactly should I add to the default backends? `company-capf` is already there.

And `company-elisp` isn't, if you have a recent enough Emacs.

**Comment by tuhdo** [comment] 2015-02-05 13:58
Sorry it was my customization. Anyway, we should leave this issue open hopefully it will be implemented in a few more years or someone creates an external package that integrate with `flx`.

**Comment by dgutov** [comment] 2015-02-05 16:33
No need: it's a duplicate of #47.

**Closed by dgutov** 2015-02-05 16:33 UTC

**Comment by jasonm23** [comment] 2015-05-03 00:51
Please add a duplicate label to this.

**Comment by dgutov** [comment] 2015-05-07 00:50
@jasonm23 Ok, added.

**Comment by jasonm23** [comment] 2015-05-07 01:03
Cheers
