### ISSUE TITLE
Garbled candidates when using partial-completion style together with grouped backends company-capf and company-dabbrev

### ISSUE THREAD

**Issue by terlar** [company-mode/company-mode#1051] opened 2021-01-13 12:21 UTC
If you are using grouped backend `'((company-capf company-dabbrev))` together with `partial-completion` the candidates will be messed up both in display and in selection and will result in invalid completions.

Steps to reproduce with `emacs -Q`:
1. Evaluate the following:
```
(require 'company)
(setq completion-styles '(partial-completion))
(setq company-backends '((company-capf company-dabbrev)))
(emacs-lisp-mode)
(company-mode 1)
```

2. Start writing `(c-dabbrev`.
3. Witness this:
![Screenshot from 2021-01-13 13-20-46](https://user-images.githubusercontent.com/280235/104451700-30fecd00-55a2-11eb-9535-f97f695189fd.png)

Thanks to @oantolin for helping me find a minimal reproducible use case:
https://github.com/oantolin/orderless/issues/23#issuecomment-759119899

**Comment by dgutov** [comment] 2021-01-14 00:33
Hi! Thanks for the report. It's actually a duplicate of #584, which is pretty old now.

I have a workaround which effectively disables the `keep-prefix` mechanics in this case, but that's probably the best we can do.

Aside from that, you probably want to use `company-dabbrev-code` and not the plain `company-dabbrev` in your config. Which doesn't have this problem.

**Closed** 2021-01-14 00:35 UTC
