### ISSUE TITLE
Icon or fixed-width text in front of candidates

### ISSUE THREAD

**Issue by Sarcasm** [company-mode/company-mode#756] opened 2018-01-27 12:25 UTC
Hello Dimitry,

As a follow up to your comment here:
- https://github.com/company-mode/company-mode/issues/208#issuecomment-325731775

I'm wondering how you feel to add support for a fixed-width text/area in front of all completion items, to allow backends to represent the candidate "kind"?

Something akin to VS Code (and other IDEs before):

![image](https://user-images.githubusercontent.com/424046/35471850-bfb795c0-0363-11e8-9be0-f56682ccdd0e.png)

The text should be fixed-width or upper-bounded so that the candidates are still well aligned.
An icon or a short string like, e.g. `<f>` for functions, could be used.

**Comment by stardiviner** [comment] 2018-01-30 04:21
I think this could be an option.

**Comment by dgutov** [comment] 2018-01-30 22:19
We can try. VS Code has a fixed set of icons (right?), we could add those, too. If they're small enough, 

I wonder how well this is going to work with certain backends, though. Right now, `elisp-completion-at-point` shows `<f>` as the annotation (sometimes), so a) it will probably need some adapter, b) exchanging these letters for an icon at the beginning of every line might, or might not, look too noisy.

To expand on that: right now, the aforementioned backend has non-empty annotations when they show the type. We'll exchange that for icons at bol, and no annotations? Or, having annotations show the arglists might be a rather striking change.

**Comment by Sarcasm** [comment] 2018-02-01 22:08
> VS Code has a fixed set of icons (right?),

Looks like it:
- https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions

To be honest, I'm wondering, how to add icon to Emacs?
Via a font or some svg/bitmap support can be detected?

I agree that it may be challenging to have something uniform across backends, but should be possible for the smarter ones. Not sure what to do with mixed backend or such but I think VS Code has "intelligent" backend, and also "abbrev-like" backend merged, with lower priority. They categorize the latter as "global identifier". (I'm not sure what I'm saying).

> We'll exchange that for icons at bol, and no annotations?

I guess so.
Personnally, I like the arglist in annotation, combined with snippets post-action it's really nice, but this is true in C++, where you can have multiple identifiers with different meanings, in Lisp you don't have this ambiguity.

**Comment by stardiviner** [comment] 2018-02-02 01:16
I guess you are saying company-mode can provide a uniform candidate types to match most easy case. For example: variable, function, struct, class, instance, etc. Then show them as icon. (I think this represent icon method must be very lightweight to avoid affect the company-mode popup tooltip performance.) About other extra backends might not in list. I think we should welcome those extra backends user to notify the developer to add this new feature support. This is a community. right.

**Comment by dgutov** [comment] 2018-02-02 13:53
SVG, or even PNG, if you prefer higher compatibility (I'm fine with either). Not sure about fonts (harder to install than just providing some image files), but that might work too.

Try `(insert-image-file "path/to/image/file.ext")` in scratch.

> some svg/bitmap support can be detected?

Calling `image-type-available-p` and doing a fallback to text should be good enough, I think.

> Not sure what to do with mixed backend

Mixed backends (grouped, in Company terms) will work. Like you said, VS Code has an icon for dabbrev, it's a decent approach.

I'm more worried about `company-capf` and the CAPF backends it uses. They'll need to continue working inside `completion-at-point` UI too. Luckily, `elisp-completion-at-point` is likely the only one such, for now, that puts type symbol into annotations.

> Personnally, I like the arglist in annotation

I've seen some people prefer type symbols, but they also customize the tooltip to put them all on the right. Maybe the "before the first column" position will satisfy them too, or we can make it customizable later.

**Comment by dgutov** [comment] 2018-02-02 13:54
> For example: variable, function, struct, class, instance, etc. Then show them as icon

Right.

**Comment by stardiviner** [comment] 2018-02-02 14:20
> Maybe the "before the first column" position
I would like see company-mode can show annotations before the tooltip first column as an option. Keep candidate as current align offset. Like this:
```
sys.path.dir
           [f] directory
           [f] dim
           [v] dict
```

What if the candidate offset already at leftest position of buffer? Then how to show those annotations?

**Comment by dgutov** [comment] 2018-02-02 22:46
You probably meant:

```
sys.path.dir
     [f] directory
     [f] dim
     [v] dict
```

> What if the candidate offset already at leftest position of buffer?

Just like when there's not enough space to the right, or below, move the popup a bit (and yeah, then it won't be so well aligned). That might be different for the childframe-based popup, though.

**Comment by stardiviner** [comment] 2018-02-03 01:40
> > You probably meant:
> 
> sys.path.dir
>      [f] directory
>      [f] dim
>      [v] dict
> 
Yeah, because of the format.

> Just like when there's not enough space to the right, or below, move the popup a bit (and yeah, then it won't be so well aligned). That might be different for the childframe-based popup, though.

I have tried `company-childframe`. Comparing with default popup, it is not smoothly as default popup. Don't know how to describe it. Just not smooth. Like some popup UI.
> move the popup a bit
I think this is acceptable.

**Comment by dgutov** [comment] 2018-02-03 14:47
> Comparing with default popup, it is not smoothly as default popup

Please file an issue. Hopefully this is fixable.

**Comment by sebastiencs** [comment] 2018-03-17 21:29
I just made a front-end to display icons with candidates: https://github.com/sebastiencs/company-next

**Comment by dgutov** [comment] 2018-03-17 21:39
Why not company-plus-plus or company-much-better?

The screenshot is pretty nice, though.

**Comment by sebastiencs** [comment] 2018-03-17 21:59
Honestly I get that name while typing `mkdir` in my shell, so there is no particular reason.
> The screenshot is pretty nice, though


Thanks

**Comment by dgutov** [comment] 2018-03-17 22:25
A bit presumptuous, isn't it? Especially since the code doesn't look like you're preparing it for upstreaming.

I'd prefer if you used just about anything more descriptive. `company-pretty-tooltip`, for instance. Or `company-with-colors-and-icons`. :smiley:

**Comment by sebastiencs** [comment] 2018-03-18 18:27
> Why not company-plus-plus or company-much-better?

I wasn't sure if it was sarcasm, but since @Sarcasm is here I should have known :)

Well I must admit I don't see the point between `company-next` and `company-much-better`, `company-plus-plus` or something similar.
Obviously no offense was intended, sorry if it feels like that, I will change the name ;)

> Especially since the code doesn't look like you're preparing it for upstreaming

I didn't expect/think it was possible, what makes it incompatible for upstreaming ?

**Comment by Sarcasm** [comment] 2018-03-18 19:05
I don't think @dgutov think it's incompatible, just that it's does not look like it was intended to upstream it.

It look gorgeous but personally I think it would be more beneficial for the whole community to upstream it. Especially since Dmitry seems interested by the idea.

The barrier to entry may be higher though, because to be really easier to use/install, I think one would need to change the following:
- Emacs 25 support (I believe this is the childframe that mainly impose this, which is a separate issue than just icons)
- use image instead of icons-in-terminal, at least optionally

However I'm not Dmitry, so don't take my word for it.
In my opinion it's more beneficial, because I think company-next solves your issue, but for me, who is somewhat comfortable to Emacs, it's still not easy to just test it/configure it.
It's one more package to maintain, I have to update my Emacs at home and work to use Emacs 26, and I also have to understand icons-in-terminal, configure my system, etc.

If instead I could just upgrade company-mode, and read about the feature/configuration from release notes, that would be awesome.

Great work anyway, I do think the annotation could use some work, but that's just a matter of taste.

**Comment by dgutov** [comment] 2018-03-18 21:45
> I wasn't sure if it was sarcasm

It was. With apologies to actual @Sarcasm.

> sorry if it feels like that, I will change the name ;)

Thank you. I think `company-next` implies either it being the next version of `company` (like a bleeding edge/staging code, or something like that), or a package that definitely supersedes it in all important respects.

> what makes it incompatible for upstreaming?

Not incompatible. Just didn't look like it's your intention. You'll need to sign the copyright assignment anyway.

It looks like a full rewrite, instead of being based on top of company-pseudo-tooltip. Lots of unnecessary changes, the diff will be hard to read (and, thus, evaluate). It's using a different style, with `dash` and stuff (which would've been better added later, as a refactoring).

`icons-in-terminal` is not in GNU ELPA, so we can't use it, too.

And, like @Sarcasm mentioned, it's conflating the use of child frame with the use of icons. If we just add icons to the built-in frontend, `company-childframe` should pick up that change automatically, BTW.

Finally, I'm not so hot on the use of different colors for different backends. I think icons should be enough. But we can discuss that separately later. Maybe plug in some customization point for that.

**Comment by sebastiencs** [comment] 2018-03-19 22:39
> use image instead of icons-in-terminal, at least optionally

Yes I did plan to provide other ways to insert icons and images are probably the most portable way.
`icons-in-terminal` is just a `.ttf` file to install though

I understand your concern about emacs 25.
I tried to use icons with `company-pseudo-tooltip` but as most of icons (from font) have a variable width I quickly gave up and start to write `company-next`. Child frames have many advantages.
I didn't try with images, that might be a solution for `company-pseudo-tooltip`

> Great work anyway, I do think the annotation could use some work, but that's just a matter of taste.

Thanks. What kind of work ? Any ideas for improvement is more than welcome :)

> It looks like a full rewrite, instead of being based on top of company-pseudo-tooltip

Most of the code is related to the frame size and its position.
Correct me if I'm wrong but the `company-pseudo-tooltip` code reconstruct the whole strings on every `company-select-[next,prev]`, which is not necessary in my case, as it is a buffer, I just change the `point` and move an overlay.
I don't see which part of `company-pseudo-tooltip` I could reuse, am I missing something ?

**Comment by dgutov** [comment] 2018-03-19 22:55
> Most of the code is related to the frame size and its position.

So, what's wrong with company-childframe? Or using posframe? Honest question. Are the APIs bad, or something?

> which is not necessary in my case

Considering most of the time the user's typing changes the list of available completions, I'm not sure you're buying a lot of extra performance with that. But yeah, scrolling might be better.

> I don't see which part of company-pseudo-tooltip I could reuse, am I missing something?

`company-fill-propertize`, for instance. And it looks like you forgot to apply at least some of the faces.

And whatever for are you providing your own faces? Even using your own colors for `company-box-candidate`? Lots of existing themes customize company's faces. That will make their job harder.

**Comment by sebastiencs** [comment] 2018-03-21 00:00
I just took a look at `posframe`, It seems too generic to be use with a `company` front-end.
See for yourself, you can compare `company-box` and `company-childframe`.

> company-fill-propertize, for instance

Yes, I could. But what about the colors for backends or the icons.
Also, the function does some calculation that are not necessary in my case, for example I use a `display` property to align annotations.
Sorry if it annoys you that I didn't made `company-box` on top of the built-in front-end. But I don't think I did bad choices, considering they have differents constraints.

I agree that my faces are useless though

**Comment by dgutov** [comment] 2018-03-21 11:18
> See for yourself, you can compare company-box and company-childframe.

I might have a guess why you think that, but I'm not 100% sure.

> But what about the colors for backends or the icons.

Well, yes, the idea would be to extend. Just like one does when creating a patch with new functionality.

To clarify my previous statement, you don't seem to apply the search faces. Does company-box handle the search commands at all? How about `company-search-toggle-filtering`?

> Sorry if it annoys you that I didn't made company-box on top of the built-in front-end. But I don't think I did bad choices, considering they have differents constraints.

Now that the name is changed, I have little reason to be annoyed. Please go ahead and experiment.

If you ever want to reintegrate, though, we'll have to deal with harder questions, such as what to do about the users of Emacs-in-terminal. I don't see why they shouldn't see icons (monospaces ones are probably not too hard to find), or even backend colors, if we come to an agreement on that.

**Comment by sebastiencs** [comment] 2018-03-22 19:09
> Does company-box handle the search commands at all?


Yes I didn't implement any search commands, yet. 
> If you ever want to reintegrate, we'll have to deal with harder questions

Yes sure.
For terminals, I think that the difficulty will be to find icons that are availables with **all** fonts.

**Comment by dgutov** [comment] 2018-03-22 21:13
> Yes I didn't implement any search commands, yet.

**Comment by dgutov** [comment] 2018-03-22 21:21
> Yes I didn't implement any search commands, yet.

The commands are there. All other frontends work fine with them. The fact that you chose to optimize by defining your own remappings... let's see how you feel about it later.

> For terminals, I think that the difficulty will be to find icons that are availables with all fonts.

Okay. If all else fails, though, we could use letters instead.

**Comment by dgutov** [comment] 2020-03-18 18:58
Continuing on from #962:

@galeo

> These icons are just text characters and can be displayed in the default tooltip frontend.

To be clear, are you using the default frontend, or the child frame based one?

Speaking of the font, the one you are using is not free, right? We'll need some default settings that would work out of the box, across operating systems.

What's your intention regarding your code? Are you going to create a third-part frontend, or a plugin that works via advice? Or do you intend to contribute the code back to the out-of-the-box experience?

The changes to backends are relatively easy to do (where the required info present at all), but I'd rather see a clearer picture first, implementation-wise. Preferably as a PR.

**Comment by galeo** [comment] 2020-03-19 13:19
> To be clear, are you using the default frontend, or the child frame based one?

I'm using the default frontend.

> Speaking of the font, the one you are using is not free, right? We'll need some default settings that would work out of the box, across operating systems.

Yes. It's not free. I've tried to find another icon font, and I think [Symbola](http://users.teilar.gr/~g1951d/) is a good choice. You can easily find the similar symbol icons used in my screenshot in its [character repertoire](http://users.teilar.gr/~g1951d/Symbola.pdf). It is not available for download right now, and an  updated version should be available when Unicode version 13 is released. However, people could download its version 12.00 from [here](https://web.archive.org/web/20190608100449/http://users.teilar.gr/~g1951d/Symbola.zip).

I really hope this feature can be provided by company itself, as you said, it can give users out-of-the-box experience. I probably won't contribute the implementation code. One reason is that I think it really simple, just as I explained before. It may be better for you @dgutov to implement the code yourself, better design and higher quality. Another reason is that I haven't signed the fsf paper. 

You may need to pay attention to the `window-width` in `company--create-lines` and alignment issues when adding icons. The problem now is that we need to define a set of supported symbol types and then convert the type information extracted from different backends. We may simply use the symbol kind names defined by [LSP](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol). In addition, consider how to facilitate user customization.

As for supporting image icons, I think it can be considered later. 

Thanks.

**Comment by dgutov** [comment] 2020-03-19 13:55
Yes, I was also thinking the LSP's list of symbol kinds can be a good choice.

As for the rest, the implementation shouldn't be hard, but it comes with a set of choices (regarding the font, the setup instructions, and the way for the user to customize all this) which need some consideration. I'm not really motivated by this feature myself, so a) my priorities on how to spend free time lie elsewhere, b) someone who's going to use is is likely to make better "soft" decisions in this list. Of course, I would review the result carefully.

So please feel free to come back to this anytime, or let's see if anybody else picks up the torch. As for signing the papers, it's not particularly hard, unless your employer claims all your free time.

**Comment by mohkale** [comment] 2020-12-22 23:03
Would it be possible to simply leave all of this choice up to the user?

Personally I don't expect or want company it-self to attach icons to completion candidates, I'd prefer if company just passed the candidate and desired width of each line to a user-configurable function that can format it as we see fit.

Looking at company-box it seems that it mostly just looks for different text-properties and then tries to map them into tyes (annotation, snippet, variable, function, etc.) it then maps those types to user-configured icons. Looking at this issue the main reason we don't seem to have anything in company yet to address this is due to concerns with fonts being available, images being supported, sizing, etc. If that's the case than I'd just like to suggest we don't bother. Let the users setup icons and make sure they look right for their use cases, and allow company to let users alter the formatting of displayed candidates as they see fit (including icons if they want). I believe #996 was going down this route but was rejected due to issues with images.

Personally I'll just be prefixing each line with an icon so in my case it'll probable be something like.

```lisp
(defun my-company-format-function (cand width)
  (let ((res (company-default-format-function cand (- width 2)))
        (icon (my-company-icon-finder cand)))
    (concat icon " " res)))

(setq company-format-function 'my-company-format-function)
```

Of course I'll also be adding fallbacks and ensuring `width > 2` but that's the general form.

Thoughts?

S.N. I would use company-box but the lack of terminal support makes me have to look elsewhere.

**Comment by dgutov** [comment] 2020-12-23 20:14
The exact presentation logic should be customizable, yet. Via format-function like you shown or similar.

#996 is not entirely dead, see the subsequent discussion. I think @yyoncho is still preparing the alternative PR.

**Comment by mohkale** [comment] 2021-03-28 17:50
Just an update @dgutov has merged in a new `company-format-margin-function` :-)

**Comment by dgutov** [comment] 2021-03-28 18:05
Yup :-) Thanks for the discussion here, closing.

**Closed by dgutov** 2021-03-28 18:05 UTC
Labels: wishlist

**Comment by mohkale** [comment] 2021-03-28 18:34
@dgutov 

I'm having some issues with the new margin function, it looks like when the backend adds annotations to candidates the margin function doesn't seem to be included in the output?

**Comment by yyoncho** [comment] 2021-03-28 18:48
@mohkale  - the prefix does not show because you are in the first position.

**Comment by mohkale** [comment] 2021-03-28 18:49
@yyoncho 

> the prefix does not show because you are in the first position.

I'm not sure what you mean, could you clarify?

**Comment by yyoncho** [comment] 2021-03-28 18:50
Press SPC SPC and then initiate the completion(for the second pic)

**Comment by mohkale** [comment] 2021-03-28 18:52
@yyoncho 

Thanks, the icons showed up when I did that... but why?

**Comment by dgutov** [comment] 2021-03-28 20:34
> Is this intentional?

Yes: to make sure completion items line up with the beginning of the prefix vertically.

Although now that margin can carry semantic information, perhaps we should reconsider doing this.

**Comment by mohkale** [comment] 2021-03-28 22:29
> Although now that margin can carry semantic information, perhaps we should reconsider doing this.

Personally I'm not a big fan of the margin sometimes being there and sometimes not so I vote for changing this.

Alternatively I've been looking back at neovim and some of the cool new stuff that's been popping up and I'm quite fond of [this](https://github.com/onsails/lspkind-nvim) plugin putting icons after the candidate but before the annotation. That could be a nice workaround if the issue is keeping the prefix seperate from the margin (although admittedly it'd look quite weird if you're not aligning annotations). Thoughts?

**Comment by dgutov** [comment] 2021-03-28 23:00
> some of the cool new stuff that's been popping up and I'm quite fond of this plugin putting icons after the candidate but before the annotation

Are these annotations "real"? One part duplicates the kind in text, another just says [LSP]...? :confused: 

> Thoughts?

I'm not a fan of how it looks on the screenshot. Though a different screenshot with more realistic annotations could leave a different impression. Perhaps *after* the annotation could be a better choice, right before the scroll bar.

In any case, it seems like you might be asking for a configurable "template" for rendering popup lines, so that you'd be able to put the icon wherever. I like the idea of that, but somebody else will probably have to take the initiative implementing it.

**Comment by mohkale** [comment] 2021-03-28 23:18
> Are these annotations "real"? One part duplicates the kind in text, another just says [LSP]...? confused

I think the LSP is an indicator for where that completion candidate is coming from. So effectively a label for the vim equivalent of `company-backends`. As for the text copy of the icon for kind, the icons were added afterwards and I presume the text version is there to be more explicit. So these annotations are real... they just aren't very space efficient.

> In any case, it seems like you might be asking for a configurable "template" for rendering popup lines, so that you'd be able to put the icon wherever. I like the idea of that, but somebody else will probably have to take the initiative implementing it.

Wasn't my original goal though that could be nice. For now I'll try to just get setup with the current state of things and if I feel the need for more configurability I'll open a new issue.

Thanks @dgutov and @yyoncho for all the hard work you've put into this :-).

**Comment by dgutov** [comment] 2021-03-28 23:48
> I think the LSP is an indicator for where that completion candidate is coming from. So effectively a label for the vim equivalent of company-backends. As for the text copy of the icon for kind, the icons were added afterwards and I presume the text version is there to be more explicit. So these annotations are real... they just aren't very space efficient.

Thank you for the explanation. But that's ridiculous, sorry to be blunt. Hopefully Neovim lets users customize all the duplication out.

> Wasn't my original goal though that could be nice. For now I'll try to just get setup with the current state of things and if I feel the need for more configurability I'll open a new issue

Very good.

**Comment by dgutov** [comment] 2021-03-29 02:22
> not a big fan of the margin sometimes being there and sometimes not

This should change now. :ok_man:

**Comment by dgutov** [comment] 2021-03-30 11:30
@mohkale BTW, if you wanted to propose a format-margin-funtion that works in the terminal, I'd be happy to review it.

Ideally, though, it should either require no external dependencies, or degrade gracefully when one (like `all-the-icons`?) is not found.

**Comment by mohkale** [comment] 2021-03-30 14:26
> BTW, if you wanted to propose a format-margin-funtion that works in the terminal, I'd be happy to review it.

@dgutov 

Personally I think it'd be better to move the existing vscode margin function to an external package `company-vscode-icons` rather than introduce another new-one. Plus I doubt there's enough *cool* unicode characters we can use as fallback for margin indicators without a package like `all-the-icons` so if it was going to happen it should probably be introduced in a `company-all-the-icons` package.

Also I tried out the existing vscode dark margin function in the GUI but all the images seem to be blocks.

![Screenshot_20210330_152448](https://user-images.githubusercontent.com/23294780/113005180-277e0d80-916c-11eb-9e6f-519e41d26850.png)

Is there anything I else I need to configure? I checked `(image-type-available-p 'svg)` and it says true.

**Comment by dgutov** [comment] 2021-03-30 14:40
> Personally I think it'd be better to move the existing vscode margin function to an external package company-vscode-icons rather than introduce another new-one.

And then what? Have no icons by default?

> Plus I doubt there's enough cool unicode characters we can use as fallback for margin indicators without a package like all-the-icons so if it was going to happen it should probably be introduced in a company-all-the-icons package.

While it would be nice, the fallback doesn't have to be "cool". Worst case, it could just use the letters of latin alphabet. But it would still tell a terminal user that the feature is there, and, with a little research, they can find out that there are packages to they can install to make it look nicer.

> Also I tried out the existing vscode dark margin function in the GUI but all the images seem to be blocks.

Good question. Does your Emacs display SVG files correctly in different contexts? What if you just `C-x C-f ...path/to/company/icons/vscode-dark/folder.svg`?

**Comment by mohkale** [comment] 2021-03-30 17:21
> And then what? Have no icons by default?

I suppose so, yes. From my POV it's just more stuff being loaded and distributed with company that I don't actually need. Although the same could be said for a lot of the packages I use so I honestly don't mind all that much. Just thought I'd give my two cents on the matter :smile:.

> While it would be nice, the fallback doesn't have to be "cool".

Okay, I'll send in a PR soon. Just to clarify by fallback do you mean a fallback to the graphical svgs as in the margin function checks `(display-graphic-p)` and then uses SVG or unicode depending on it, or do you mean to introduce a new margin function that users can configure independent of `(display-graphic-p)`?

> Does your Emacs display SVG files correctly in different contexts?

Seems to be working :/

![Screenshot_20210330_181912](https://user-images.githubusercontent.com/23294780/113029632-8c456200-9184-11eb-8206-6ed5646ba6f8.png)

**Comment by dgutov** [comment] 2021-03-30 18:04
> I suppose so, yes. From my POV it's just more stuff being loaded and distributed with company that I don't actually need. Although the same could be said for a lot of the packages I use so I honestly don't mind all that much. Just thought I'd give my two cents on the matter smile.

I expect a lot of users to go on using the built-in svg-based icons because they're pretty nice, and no everybody uses Emacs in terminal. But an automatic fallback to a different approach in the terminal will be best.

In general, whenever something is customizable, I always prefer to have a solid default options. Among other things, it helps iron out a lot of the issues out of the gate. And default behavior is also important.

> Okay, I'll send in a PR soon. Just to clarify by fallback do you mean a fallback to the graphical svgs as in the margin function checks (display-graphic-p) and then uses SVG or unicode depending on it, or do you mean to introduce a new margin function that users can configure independent of (display-graphic-p)?

Either can work, but I was thinking of the latter. And then also add a fourth margin function which would automatically decide which of the others to use based on what `(display-graphic-p)` returns, and on the value of `frame-background-mode`. That one should be workable as the default instead of current `nil`.

> Seems to be working :/

Hmm, quick question then: do any of the built-in backends show icons? Like `company-yasnippet` or `company-dabbrev-code`. You can invoke either of them with `M-x`.

**Comment by mohkale** [comment] 2021-03-30 20:17
> Hmm, quick question then: do any of the built-in backends show icons? Like company-yasnippet or company-dabbrev-code. You can invoke either of them with M-x.

Tried `company-yasnippet` didn't show any icons :/. Also tried in `lisp-interaction-mode`and there aren't any icons there either. My guess is because most backends don't have a `:company-kind` field yet?

**Comment by dgutov** [comment] 2021-03-30 20:22
OK. What's your value of `company-icons-root`?

Could you try stepping through `company--render-icons-margin` with Edebug to see whether it generates file names that exist on disk? Although if the file is missing, I see corresponding messages in `*Messages*` accompanying mojibake icons that you see now.

> My guess is because most backends don't have a :company-kind field yet

I've mentioned two (among several) that do. `elisp-completion-at-point` also has support for them now, but it's only in the latest master.

**Comment by mohkale** [comment] 2021-03-30 20:31
> OK. What's your value of company-icons-root?

`"/home/mohkale/.config/emacs/lisp/straight/build/company/icons/"`,

oh I'm using straight and it keeps bytecompiled elisp files seperate from the source repos which explains this. `company-icons-root` should be `"/home/mohkale/.config/dotfiles/prog/editors/emacs/lisp/straight/repos/company-mode/icons"`. Setting it to this fixed the issue.

Turns out this was just a configuration error on my part, although I'd expect straight to have copied the icons to the build directory if their part of the package. Maybe there's something we can do with the recipes to fix that :/

>  but it's only in the latest master

Just jumped to `elisp-mode` and it doesn't seem to define it. I'll have to upgrade to confrim but otherwise I don't foresee any issue there. Also thanks for the clarification, looking forward to upgrade now.

**Comment by mohkale** [comment] 2021-03-30 20:41
Changing my package recipe from:

```elisp
(use-package company
  :straight t)
```

```elisp
(use-package company
  :straight (company :files (:defaults "icons")))
```

fixed the issue. Thanks.

**Comment by dgutov** [comment] 2021-03-30 20:44
Excellent. I hope there is a centralized recipe repository that can be updated too, for everyone's benefit.

> Just jumped to elisp-mode and it doesn't seem to define it. I'll have to upgrade to confrim but otherwise I don't foresee any issue there. Also thanks for the clarification, looking forward to upgrade now.

:+1: 

I've only pushed it yesterday: https://github.com/emacs-mirror/emacs/commit/24c92b35b5ed8432e53a27ed3cb477788894ecdc
