### ISSUE TITLE
company evil conflict

### ISSUE THREAD

**Issue by hotpxl** [company-mode/company-mode#383] opened 2015-07-28 08:14 UTC
There is a conflict between `company-mode` and `evil-mode`. It happens with nearly any backend. I have a minimal `.emacs` file to reproduce the problem.

    (package-initialize)
    (require 'company)
    (add-hook 'after-init-hook 'global-company-mode)
    (setq company-idle-delay 0)
    (global-set-key (kbd "S-<tab>") 'company-complete)
    (require 'evil)
    (add-hook 'after-init-hook (lambda () (evil-mode 1)))

To reproduce the problem. Open any C++ file. Get to a point where you can get some autocompletion.

    #include <vector>

    int main() {
      std::vector<int> a;
      a. // <- cursor here
      return 0;
    }

Make sure you hadn't auto-completed anything before in this Emacs process. After you typed ".", hit <kbd>S-tab</kbd> like crazy (in fact I think you need only once to make it happen). It says `company-complete` for me, manually invoking completion. Then open Messages buffer, you will get something like:

    Error in post-command-hook (evil-repeat-post-hook): (wrong-type-argument number-or-marker-p nil)

This happens (at least) once per process. Removing `company-complete-common` from `evil-declare-change-repeat` and add it to `evil-declare-no-repeat` could make this error disappear.

**Comment by dgutov** [comment] 2015-07-28 10:10
Could you `M-x toggle-debug-on-error` and repeat that?

**Comment by hotpxl** [comment] 2015-07-28 15:54
@dgutov I have done that. But the error message is the same.

**Comment by hotpxl** [comment] 2015-07-28 15:58
I also set `debug-ignored-errors` to `nil`. Still the same.

**Comment by dgutov** [comment] 2015-07-28 16:03
Could you try that in Emacs 24.4 or newer?

**Comment by hotpxl** [comment] 2015-07-28 16:04
I am running Emacs 24.5.1 on Mac. I downloaded both packages from MELPA.

**Comment by dgutov** [comment] 2015-07-28 16:06
Ok, thanks. I'll have to try that myself.

**Comment by hotpxl** [comment] 2015-07-28 16:21
I got same behavior on Arch Linux, Emacs 24.5.1. Although key binding `<S-tab>` has to be changed to something else.

**Comment by dgutov** [comment] 2015-07-30 00:38
I've tried it. `S-<tab>` didn't work, but with binding the same command to `<backtab>` worked as expected: the first its invocation completes the method to `a.vector` and expands the arguments into template fields. No error.

What backend are you using there? Try `M-x company-diag`.

**Comment by hotpxl** [comment] 2015-07-30 07:57
The completion works itself. But if I go to `*Messages*` buffer there will be this error.

I think the point is, after you type `a.`, you have to hit `<backtab>` multiple times and really fast.

Shows its using `company-clang`.

**Comment by dgutov** [comment] 2015-07-30 12:30
Ok, I now see it too. Only works once per buffer (but I can kill it, reopen, and reproduce again), and completion works, the only visible problem is in the messages log.

@lyro Any ideas?

**Comment by hotpxl** [comment] 2015-07-31 03:05
I traced it down to somewhere in `evil` when it's trying to log the command for repeat or something. If I put it into `evil-declare-no-repeat`, then the problem goes away. But it's only a workaround.

**Comment by dubiousdavid** [comment] 2016-01-28 14:35
@hotpxl Can you paste the exact `evil-declare-no-repeat` command you are using as a workaround?

**Comment by hotpxl** [comment] 2016-01-30 07:49
@dubiousdavid Dude. This is *really* a long time ago. I can't find my workaround anymore. I guess after some time I just forgot about the bug and the error message.

From what I remember (by looking at the conversation), I think you should remove `company-complete-common` from `evil-declare-change-repeat` and add it to `evil-declare-no-repeat`. Anyways, hasn't the problem been fixed yet?

**Comment by dgutov** [comment] 2016-01-30 08:02
> Anyways, hasn't the problem been fixed yet?

No idea. @lyro hasn't answered my call here, so if the problem is still present, you better take it to the Evil:

https://bitbucket.org/lyro/evil/src/729017f7a470e372ef193ee72401e9ec68331326/evil-integration.el?fileviewer=file-view-default#evil-integration.el-294:313

https://bitbucket.org/lyro/evil/issues?status=new&status=open

**Comment by lyro** [comment] 2016-01-30 09:41
Sorry, I completely missed this issue (I'm not very active on github). 

The reason seems to be the following: Evil handles the recording of repeat information with pre and post command hooks. In your example, the pre-command-hook is called with `complete-company` as `this-command` and the post-command-hook with `complete-company-common`. The problem is that currently `complete-company` is not marked as function for change-based recording but `complete-company-common` is (change-based recording is required for completion packages, because keystrokes that would select completion candidates must not be part of the repeat information, only the change itself).
So for some reason `company-complete-common` in your example only triggers the post-command-hook but not the pre-command-hook (and I really do not know why, if it would call the pre hook then everything should work), thus some repeat information is not recorded correctly and causes the error.

In fact, the commands that should be listed as `change-based` are those that actually do buffer insertion (currently these are `company-complete-mouse, -number, -selection, -common` (no idea if this list is complete) and other commands that only select something should be ignored (e.g. `company-select-next` and friends).


Possible solutions:
* ignore `company-complete-common` completely
* list `company-complete` as change-based (`(evil-declare-change-repeat 'company-complete-common)`)

The second solution seems to work in my tests (no error and repeat works), but no idea if there are other  cases that I missed).

**Comment by dgutov** [comment] 2016-01-30 19:45
@lyro Thanks for replying.

> So for some reason company-complete-common in your example only triggers the post-command-hook but not the pre-command-hook

Maybe because `company-complete` calls `(call-interactively 'company-complete-common)`? That seems to be a legitimate thing to do.

**Comment by dgutov** [comment] 2016-01-30 19:47
> list company-complete as change-based ((evil-declare-change-repeat 'company-complete-common))

Did you mean: `(evil-declare-change-repeat 'company-complete)`?

**Comment by lyro** [comment] 2016-01-30 20:09
Yes, I did.

**Comment by dgutov** [comment] 2016-01-30 20:28
Thanks. @hotpxl  @dubiousdavid Could you please verify the solution work for you?

**Comment by dubiousdavid** [comment] 2016-01-30 22:27
Sorry for the confusion, but I actually think this is working for me properly. I just had the wrong expectations.

**Comment by hotpxl** [comment] 2016-01-31 15:40
@lyro @dgutov  I added `'company-complete` to the list of `evil-declare-change-repeat` and it solved my problem. Thanks for spending time on this. Keep up the good work :)

**Comment by dgutov** [comment] 2016-01-31 21:01
Thanks all!

**Closed by dgutov** 2016-01-31 21:01 UTC
