### ISSUE TITLE
Trigger completion when cursor is before non-blank characters.

### ISSUE THREAD

**Issue by amosbird** [company-mode/company-mode#637] opened 2017-02-06 15:58 UTC
I'd like to set company to pop out completion menu even when cursor is at
```
foo|=123
   ^
```
Is it possible?

**Comment by dgutov** [comment] 2017-02-06 23:22
Right after you typed `o`?

**Comment by amosbird** [comment] 2017-02-07 01:39
Yes, but with the suffix `=123` already typed in.

**Comment by dgutov** [comment] 2017-02-07 01:50
With `|=123`, you mean?

Works for me. What major mode you're trying it in?

**Comment by dgutov** [comment] 2017-02-07 01:51
The issues is usually not whether point is before blank characters, but whether it is before symbol constituent characters. But the exact decision depends on the backend (and your settings, of course).

**Comment by amosbird** [comment] 2017-02-07 01:54
ah, I see. It's a bad example. I meant to ask how to get completion when point is before constituent characters.

**Comment by amosbird** [comment] 2017-02-07 02:02
In fact, is it possible to get completion before any characters?

**Comment by dgutov** [comment] 2017-02-07 02:05
Not normally, but a particular backend could allow that (together with associated annoyances like having the suffix duplicated by accident).

Anyway, this is a duplicate of #340.

**Closed by dgutov** 2017-02-07 02:05 UTC
Labels: question
